import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadDivyaDesams } from "../content-lib/loader.ts";
import { allPasuramResourceUrls } from "../content-lib/pasuram-resources.ts";
import { getPasuramFileName } from "../services/pasuramResourceId.ts";

/**
 * Emits mobile/content-lib/pasuram-manifest.generated.ts: a static
 * `import` (Metro asset id) for every Pasuram PDF under
 * mobile/assets/pasurams/, keyed by the exact Prapatti URL that
 * resource-id maps to. All ~432 unique PDFs are now bundled directly
 * into the app -- there is no download step at all, offline or
 * otherwise; a Pasuram is either in this manifest (and therefore always
 * available) or it isn't referenced by any current Divya Desam record.
 *
 * Same "static import, never copy" strategy as
 * generate-content-manifest.ts's own image manifest: Metro's asset
 * pipeline does the actual bundling of the referenced bytes (`.pdf` is
 * already in Expo's default `resolver.assetExts`, confirmed empirically
 * -- no metro.config.js change was needed), this script only emits the
 * import/lookup-table glue.
 *
 * mobile/assets/pasurams/<hash>.pdf filenames come from
 * services/pasuramResourceId.ts's getPasuramFileName(url) -- the same
 * stable, URL-derived identity the (now-removed) network downloader
 * used to name its cached files. The count grew from an initial 402 to
 * 432 after an audit found 30 resource entries whose URL pointed to the
 * wrong language folder or the wrong temple entirely (see this repo's
 * commit history) -- each fix meant a genuinely new file to fetch and
 * bundle, not just a rename.
 */

const MOBILE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const ASSETS_ROOT = path.join(MOBILE_ROOT, "assets", "pasurams");
const OUTPUT_FILE = path.join(MOBILE_ROOT, "content-lib", "pasuram-manifest.generated.ts");

function identifierFor(filename: string): string {
  const base = path.basename(filename, ".pdf");
  return `pdf_${base}`;
}

function main(): void {
  const urls = allPasuramResourceUrls(loadDivyaDesams());

  const imports: string[] = [];
  const mapEntries: string[] = [];
  let missing = 0;

  for (const url of urls) {
    const filename = getPasuramFileName(url);
    const filePath = path.join(ASSETS_ROOT, filename);
    if (!fs.existsSync(filePath)) {
      missing += 1;
      console.warn(`  warning: no bundled PDF for ${url} -- expected ${filename} under mobile/assets/pasurams/`);
      continue;
    }

    const identifier = identifierFor(filename);
    const relative = path.relative(path.dirname(OUTPUT_FILE), filePath);
    imports.push(`import ${identifier} from "${relative.startsWith(".") ? relative : `./${relative}`}";`);
    mapEntries.push(`  ${JSON.stringify(url)}: ${identifier},`);
  }

  const output = `/**
 * AUTO-GENERATED by mobile/scripts/generate-pasuram-manifest.ts.
 * Do not edit by hand -- regenerate instead.
 *
 * Every import below points DIRECTLY at the real bundled PDF under
 * mobile/assets/pasurams/ for that Prapatti URL -- nothing here is
 * fetched at runtime. ${missing} url(s) referenced by the content corpus
 * had no matching bundled PDF and were skipped (see the generator's own
 * warning output).
 */
${imports.join("\n")}

/** Prapatti resource URL -> Metro-resolved bundled PDF asset. */
export const pasuramAssetByUrl: Record<string, number> = {
${mapEntries.join("\n")}
};
`;

  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output, "utf8");

  console.log(`Generated ${path.relative(path.join(MOBILE_ROOT, ".."), OUTPUT_FILE)}: ${mapEntries.length} Pasuram PDF(s) bundled (${missing} missing).`);
}

main();
