import { Directory, File, Paths } from "expo-file-system";
import * as core from "./bookOfflineCore.ts";
import type { BookDownloadResult, BookFileSystem } from "./bookOfflineCore.ts";

/**
 * Makes Library books available offline: download once into app-private
 * persistent storage (Paths.document, never public Downloads), then read
 * the local copy with zero network contact on every subsequent open.
 * This is the one place in mobile/ allowed to touch the network for this
 * feature -- see mobile/tests/offline.test.ts, which fails the build if
 * app/, components/, or content-lib/ reference fetch/XMLHttpRequest/
 * axios, and mobile/services/updateCheckService.ts for the pre-existing
 * convention this follows. (Pasurams no longer touch the network at
 * all -- every Pasuram PDF is bundled into the app, see
 * pasuramOfflineService.ts.)
 *
 * URLs mirror updateCheckService.ts's VERSION_MANIFEST_URL exactly: the
 * same GitHub Pages deploy (published by the existing, unmodified
 * .github/workflows/deploy-pages.yml) that already serves app-version.json
 * and every Divya Desam image also serves each book's JSON payload
 * (public/books/<slug>.json, generated by scripts/build-book-payloads.ts
 * -- see that script's doc comment) and its images (the same
 * public/images/ URL space components/shared/RecordImages.tsx already
 * resolves on web).
 *
 * This file is just the real expo-file-system adapter, pre-bound onto
 * the actual orchestration logic in bookOfflineCore.ts. That split
 * exists because Node's native TypeScript support refuses to strip
 * types from .ts files under node_modules, so a module with a real,
 * top-level `import ... from "expo-file-system"` crashes under
 * `node --test` regardless of whether any given code path actually uses
 * it. mobile/tests/book-offline-service.test.ts exercises
 * bookOfflineCore.ts directly, against a small in-memory fake
 * filesystem, instead of this file.
 */

const PAGES_BASE_URL = "https://vedantayojana.org";

function bookJsonUrl(bookSlug: string): string {
  return `${PAGES_BASE_URL}/books/${bookSlug}.json`;
}

const IMAGE_BASE_URL = `${PAGES_BASE_URL}/images`;

const realFileSystem: BookFileSystem = {
  get documentDirectoryPath() {
    return Paths.document.uri;
  },
  get cacheDirectoryPath() {
    return Paths.cache.uri;
  },
  fileExists(path) {
    return new File(path).exists;
  },
  fileSize(path) {
    return new File(path).size ?? 0;
  },
  readTextFile(path) {
    return new File(path).textSync();
  },
  writeTextFile(path, content) {
    new File(path).write(content);
  },
  deleteFile(path) {
    const file = new File(path);
    if (file.exists) file.delete();
  },
  deleteDirectory(path) {
    const dir = new Directory(path);
    if (dir.exists) dir.delete();
  },
  ensureDirectoryExists(path) {
    const dir = new Directory(path);
    if (!dir.exists) dir.create({ intermediates: true, idempotent: true });
  },
  moveFile(fromPath, toPath) {
    new File(fromPath).move(new File(toPath));
  },
  async downloadTextFile(url, destinationPath) {
    await File.downloadFileAsync(url, new File(destinationPath));
  },
  async downloadBinaryFile(url, destinationPath) {
    await File.downloadFileAsync(url, new File(destinationPath));
  },
};

export type { BookDownloadResult, BookFileSystem } from "./bookOfflineCore.ts";
export type { BookPayload } from "../../content-lib/mobile-content.ts";

export function isBookAvailable(bookSlug: string): boolean {
  return core.isBookAvailable(bookSlug, realFileSystem);
}

export function loadOfflineBook(bookSlug: string) {
  return core.loadOfflineBook(bookSlug, realFileSystem);
}

export function getOfflineBookImageUri(bookSlug: string, imageUuid: string): string | null {
  return core.getOfflineBookImageUri(bookSlug, imageUuid, realFileSystem);
}

/**
 * De-duplicates concurrent downloads of the SAME book -- bookOfflineCore's
 * downloadBook() deletes and recreates a shared per-slug temp directory
 * (tempBookDir()) with no locking of its own, so two independent callers
 * racing on it (e.g. LibraryBookScreen's read-online-then-download tap
 * on a chapter, and BookDownloadControl's explicit Download button,
 * firing around the same time now that chapters are never gated behind
 * downloading first) can corrupt each other's in-flight temp files --
 * confirmed on a real device: one call's `deleteDirectory(tempDir)` ran
 * between the other's `ensureDirectoryExists("<tempDir>/images")` and
 * its image download, producing a real ENOENT. Every caller for a given
 * slug now shares the one in-flight promise instead of each starting
 * its own full delete-then-redownload sequence.
 */
const inFlightDownloads = new Map<string, Promise<BookDownloadResult>>();

export function downloadBook(bookSlug: string): Promise<BookDownloadResult> {
  const existing = inFlightDownloads.get(bookSlug);
  if (existing) return existing;

  const promise = core.downloadBook(bookSlug, bookJsonUrl(bookSlug), IMAGE_BASE_URL, realFileSystem).finally(() => {
    inFlightDownloads.delete(bookSlug);
  });
  inFlightDownloads.set(bookSlug, promise);
  return promise;
}

export function deleteBook(bookSlug: string): void {
  core.deleteBook(bookSlug, realFileSystem);
}

/** The locally-recorded content hash for a downloaded book, or null if it isn't downloaded. Used by libraryCatalogService.ts to detect a stale copy against contentManifest.json. */
export function getLocalBookContentHash(bookSlug: string): string | null {
  return core.getLocalBookContentHash(bookSlug, realFileSystem);
}
