/**
 * AUTO-GENERATED by mobile/scripts/generate-pasuram-archive.ts.
 * Do not edit by hand -- regenerate instead.
 *
 * The single import below is the one thing Metro actually bundles into
 * the app for Pasurams: a solid zstd archive of every optimized PDF (see
 * the generator script's own doc comment for why). services/
 * pasuramArchive.ts unpacks it into app-private storage once, on first
 * need, using fzstd (pure JS, no native module) and services/
 * pasuramTar.ts's ustar parser. Split into its own file, separate from
 * pasuram-manifest.generated.ts's pure data, because plain Node cannot
 * parse a binary Metro asset import at all.
 */
import pasuramArchiveAsset from "../assets/pasurams-archive.generated.zst";

export { pasuramArchiveAsset };
