/**
 * AUTO-GENERATED by mobile/scripts/generate-pasuram-manifest.ts.
 * Do not edit by hand -- regenerate instead.
 *
 * Every import below points DIRECTLY at the real bundled PDF under
 * mobile/assets/pasurams/ for that Prapatti URL -- nothing here is
 * fetched at runtime. 0 url(s) referenced by the content corpus
 * had no matching bundled PDF and were skipped (see the generator's own
 * warning output).
 */
import pdf_467afa852da5e07b93b4bbaae6cd5b52 from "../assets/pasurams/467afa852da5e07b93b4bbaae6cd5b52.pdf";
import pdf_cea3165fd24b9126a8bcf98c53a87184 from "../assets/pasurams/cea3165fd24b9126a8bcf98c53a87184.pdf";
import pdf_ccd7d82c1569e55f0a289f5b78afa515 from "../assets/pasurams/ccd7d82c1569e55f0a289f5b78afa515.pdf";
import pdf_31f515a698fe9bcc75990ed8f84388cb from "../assets/pasurams/31f515a698fe9bcc75990ed8f84388cb.pdf";
import pdf_b97f96b8ebe37e1ae3f30fdaa368596f from "../assets/pasurams/b97f96b8ebe37e1ae3f30fdaa368596f.pdf";
import pdf_f1f15e06aaa87503c3fb69c32a1adfc8 from "../assets/pasurams/f1f15e06aaa87503c3fb69c32a1adfc8.pdf";
import pdf_9e9bd7d8ae1067e0d829363ae1bf0c03 from "../assets/pasurams/9e9bd7d8ae1067e0d829363ae1bf0c03.pdf";
import pdf_41a71e076bfc27782f6118dab98eae3e from "../assets/pasurams/41a71e076bfc27782f6118dab98eae3e.pdf";
import pdf_514706885d7dfcdfd94531f93a3a9686 from "../assets/pasurams/514706885d7dfcdfd94531f93a3a9686.pdf";
import pdf_ff62fa134bbb6e695dfeaeea724d5a8a from "../assets/pasurams/ff62fa134bbb6e695dfeaeea724d5a8a.pdf";
import pdf_54e51f6845f4bcabbecaf45c61caec3e from "../assets/pasurams/54e51f6845f4bcabbecaf45c61caec3e.pdf";
import pdf_addb54d96ac0a9baf0b3b010a5a10c98 from "../assets/pasurams/addb54d96ac0a9baf0b3b010a5a10c98.pdf";
import pdf_c123e72fb52e1b9d05723d76e730d124 from "../assets/pasurams/c123e72fb52e1b9d05723d76e730d124.pdf";
import pdf_646144e15a346f04629d6ca837b02af0 from "../assets/pasurams/646144e15a346f04629d6ca837b02af0.pdf";
import pdf_923d6d7ea8c6ef607354ae5c0e2c2c58 from "../assets/pasurams/923d6d7ea8c6ef607354ae5c0e2c2c58.pdf";
import pdf_9303a28c963dfef63d63293b0bf61c66 from "../assets/pasurams/9303a28c963dfef63d63293b0bf61c66.pdf";
import pdf_91f8d2e5757790954aeea6d3e420c954 from "../assets/pasurams/91f8d2e5757790954aeea6d3e420c954.pdf";
import pdf_b187de4d88f0060367f3569f033e0189 from "../assets/pasurams/b187de4d88f0060367f3569f033e0189.pdf";
import pdf_6eb2008d5b6c551300367d1504d20d50 from "../assets/pasurams/6eb2008d5b6c551300367d1504d20d50.pdf";
import pdf_2f33bbb970c38c8880c1a11619acbd79 from "../assets/pasurams/2f33bbb970c38c8880c1a11619acbd79.pdf";
import pdf_600d2b39d41344e480e3b7b524942e69 from "../assets/pasurams/600d2b39d41344e480e3b7b524942e69.pdf";
import pdf_124af85ee1918c8d63741e048d12ae7b from "../assets/pasurams/124af85ee1918c8d63741e048d12ae7b.pdf";
import pdf_b8e9c60fbdd19d1a56547228227ab54f from "../assets/pasurams/b8e9c60fbdd19d1a56547228227ab54f.pdf";
import pdf_8f4549dbc1b7b03e6779170cf7aa1c00 from "../assets/pasurams/8f4549dbc1b7b03e6779170cf7aa1c00.pdf";
import pdf_0cd460eeed23a2e692eda05ed660c89c from "../assets/pasurams/0cd460eeed23a2e692eda05ed660c89c.pdf";
import pdf_76612f6186454882244f4431a0ca8cd2 from "../assets/pasurams/76612f6186454882244f4431a0ca8cd2.pdf";
import pdf_8ea1f297605e3cab1b447d95db92632d from "../assets/pasurams/8ea1f297605e3cab1b447d95db92632d.pdf";
import pdf_9a5498ec369fda1aa9d1a9e7c500e31a from "../assets/pasurams/9a5498ec369fda1aa9d1a9e7c500e31a.pdf";
import pdf_2dbbc2b8cf08d1c5cd25d973dfb1e939 from "../assets/pasurams/2dbbc2b8cf08d1c5cd25d973dfb1e939.pdf";
import pdf_8691a5ba68fee519908e654207edcbb7 from "../assets/pasurams/8691a5ba68fee519908e654207edcbb7.pdf";
import pdf_347db061d536ef2326b78fd3811eb4f4 from "../assets/pasurams/347db061d536ef2326b78fd3811eb4f4.pdf";
import pdf_d0c208c705ffdcf7eb1ab8dc6e41983f from "../assets/pasurams/d0c208c705ffdcf7eb1ab8dc6e41983f.pdf";
import pdf_04a01857e104384ba60be707db447a9e from "../assets/pasurams/04a01857e104384ba60be707db447a9e.pdf";
import pdf_83d7dd6fa62e784b557703e297a99fc7 from "../assets/pasurams/83d7dd6fa62e784b557703e297a99fc7.pdf";
import pdf_b3f0b287018cc6d7361d8311fae41d52 from "../assets/pasurams/b3f0b287018cc6d7361d8311fae41d52.pdf";
import pdf_bfab3d1a5aaec9af390804489e1f5148 from "../assets/pasurams/bfab3d1a5aaec9af390804489e1f5148.pdf";
import pdf_90c4abf8019e9e009e2ac2e02c21da50 from "../assets/pasurams/90c4abf8019e9e009e2ac2e02c21da50.pdf";
import pdf_d92c60a904bfc598311cbc8abce61d08 from "../assets/pasurams/d92c60a904bfc598311cbc8abce61d08.pdf";
import pdf_be0a6d62b14271ae9629cbec57c5f529 from "../assets/pasurams/be0a6d62b14271ae9629cbec57c5f529.pdf";
import pdf_66d4be8a2a09c0f28c599a221111bb7c from "../assets/pasurams/66d4be8a2a09c0f28c599a221111bb7c.pdf";
import pdf_4820c888f3949c8358fd2e3de62589c6 from "../assets/pasurams/4820c888f3949c8358fd2e3de62589c6.pdf";
import pdf_e12de99ae58e2c7c15fa515d7adfc76e from "../assets/pasurams/e12de99ae58e2c7c15fa515d7adfc76e.pdf";
import pdf_31a1c116a887b675276992c7271ac87f from "../assets/pasurams/31a1c116a887b675276992c7271ac87f.pdf";
import pdf_4cd1d34d1388f43d24bb5490a74af5b9 from "../assets/pasurams/4cd1d34d1388f43d24bb5490a74af5b9.pdf";
import pdf_f95a170c6593d2cde21b10fa3d6ea7e5 from "../assets/pasurams/f95a170c6593d2cde21b10fa3d6ea7e5.pdf";
import pdf_c1d81873117034d4235ed47778f92516 from "../assets/pasurams/c1d81873117034d4235ed47778f92516.pdf";
import pdf_f8ccdd5934652dd038ac8539430b4155 from "../assets/pasurams/f8ccdd5934652dd038ac8539430b4155.pdf";
import pdf_09202bd7258431fe74c835118628d046 from "../assets/pasurams/09202bd7258431fe74c835118628d046.pdf";
import pdf_d97cba806c0f36a7272ca477faf63f6e from "../assets/pasurams/d97cba806c0f36a7272ca477faf63f6e.pdf";
import pdf_040eacd95f06127ea17c836e8b3a63ef from "../assets/pasurams/040eacd95f06127ea17c836e8b3a63ef.pdf";
import pdf_3e59e91e3b437b47983b72de670a26ae from "../assets/pasurams/3e59e91e3b437b47983b72de670a26ae.pdf";
import pdf_58654474fcc28a6429ef22b6b6d5540b from "../assets/pasurams/58654474fcc28a6429ef22b6b6d5540b.pdf";
import pdf_d36eac863af9c2436b39356130174af7 from "../assets/pasurams/d36eac863af9c2436b39356130174af7.pdf";
import pdf_859ef6bcb02bf405966143223b1e6c83 from "../assets/pasurams/859ef6bcb02bf405966143223b1e6c83.pdf";
import pdf_887565567ad5ba9f85a4c70e0de6a6e8 from "../assets/pasurams/887565567ad5ba9f85a4c70e0de6a6e8.pdf";
import pdf_fd0667dffbbf7b60b6ffd2cac623ccb8 from "../assets/pasurams/fd0667dffbbf7b60b6ffd2cac623ccb8.pdf";
import pdf_542e5d7e7d2996bf41be177f3dd1b39d from "../assets/pasurams/542e5d7e7d2996bf41be177f3dd1b39d.pdf";
import pdf_603ce4336a9ec2bfa63284b9241b15ea from "../assets/pasurams/603ce4336a9ec2bfa63284b9241b15ea.pdf";
import pdf_df35c86eee3c2fdf3bdac8def9ebdafc from "../assets/pasurams/df35c86eee3c2fdf3bdac8def9ebdafc.pdf";
import pdf_44340f241b98300e9f4aab50c3d2891f from "../assets/pasurams/44340f241b98300e9f4aab50c3d2891f.pdf";
import pdf_b61dfee72d010525d308b772a4dd1e72 from "../assets/pasurams/b61dfee72d010525d308b772a4dd1e72.pdf";
import pdf_e19ba9ce3431213a7079aa1fabe1f79e from "../assets/pasurams/e19ba9ce3431213a7079aa1fabe1f79e.pdf";
import pdf_dece0bd58e148dee049717f8e16f15f9 from "../assets/pasurams/dece0bd58e148dee049717f8e16f15f9.pdf";
import pdf_d2f32d6a58911c12d52ad2f0ac2f9c2b from "../assets/pasurams/d2f32d6a58911c12d52ad2f0ac2f9c2b.pdf";
import pdf_623c954516bb1c122ec2ed6ef99c4f59 from "../assets/pasurams/623c954516bb1c122ec2ed6ef99c4f59.pdf";
import pdf_fcd13994d4b972fec29e4cfa904537ff from "../assets/pasurams/fcd13994d4b972fec29e4cfa904537ff.pdf";
import pdf_19a5cd6af013b5b522e15c9ce0019649 from "../assets/pasurams/19a5cd6af013b5b522e15c9ce0019649.pdf";
import pdf_074489fdf89e2b8766b7e1bafed58436 from "../assets/pasurams/074489fdf89e2b8766b7e1bafed58436.pdf";
import pdf_cb104352eeae7f85d146ffcc72ea3c9d from "../assets/pasurams/cb104352eeae7f85d146ffcc72ea3c9d.pdf";
import pdf_d078e39ef11395084dbbc88d93f07806 from "../assets/pasurams/d078e39ef11395084dbbc88d93f07806.pdf";
import pdf_f0bd0421801019105c359e918ebf2c65 from "../assets/pasurams/f0bd0421801019105c359e918ebf2c65.pdf";
import pdf_ab283be1ae3e626c49d13db46839cd31 from "../assets/pasurams/ab283be1ae3e626c49d13db46839cd31.pdf";
import pdf_c6f30bd3363e956abd2420dc12fe0165 from "../assets/pasurams/c6f30bd3363e956abd2420dc12fe0165.pdf";
import pdf_dc3af2cac0b19f1f2838ec727b8b8f09 from "../assets/pasurams/dc3af2cac0b19f1f2838ec727b8b8f09.pdf";
import pdf_96b78212638e6a7c8c8de5c86a1bd951 from "../assets/pasurams/96b78212638e6a7c8c8de5c86a1bd951.pdf";
import pdf_6961d2f17b6637c4940264fd774c0529 from "../assets/pasurams/6961d2f17b6637c4940264fd774c0529.pdf";
import pdf_8b72e9c7dc7bc5bebc38908f2351a72a from "../assets/pasurams/8b72e9c7dc7bc5bebc38908f2351a72a.pdf";
import pdf_e7c476ab8031c07c906d267b7ec6e5d4 from "../assets/pasurams/e7c476ab8031c07c906d267b7ec6e5d4.pdf";
import pdf_fb2d90bc0c750f2ceec1c801b7a15ce3 from "../assets/pasurams/fb2d90bc0c750f2ceec1c801b7a15ce3.pdf";
import pdf_ebe9efddc7c4976b16fc0c8e6bcb1567 from "../assets/pasurams/ebe9efddc7c4976b16fc0c8e6bcb1567.pdf";
import pdf_6d40338d62faa20b1737f5513f692c8c from "../assets/pasurams/6d40338d62faa20b1737f5513f692c8c.pdf";
import pdf_a46ccd8bad1fafb30ef4b701b1596ea9 from "../assets/pasurams/a46ccd8bad1fafb30ef4b701b1596ea9.pdf";
import pdf_d597d71c0c874cfb612426b7135b9fd5 from "../assets/pasurams/d597d71c0c874cfb612426b7135b9fd5.pdf";
import pdf_1bdb515e3be0700c909d2d9471fad67b from "../assets/pasurams/1bdb515e3be0700c909d2d9471fad67b.pdf";
import pdf_3d683867ba7d4efbe60ded8a5258ee69 from "../assets/pasurams/3d683867ba7d4efbe60ded8a5258ee69.pdf";
import pdf_3bf0482f2666190093e66342f7f51be9 from "../assets/pasurams/3bf0482f2666190093e66342f7f51be9.pdf";
import pdf_384c30b4aa34ebc21434a5ef613159fa from "../assets/pasurams/384c30b4aa34ebc21434a5ef613159fa.pdf";
import pdf_2d6b3c3ab8f83a3614d52c7f23b2f749 from "../assets/pasurams/2d6b3c3ab8f83a3614d52c7f23b2f749.pdf";
import pdf_6074922f04bf906977e036c9233b4b4d from "../assets/pasurams/6074922f04bf906977e036c9233b4b4d.pdf";
import pdf_2ff756439fdf803a326fecdfa48a5a3a from "../assets/pasurams/2ff756439fdf803a326fecdfa48a5a3a.pdf";
import pdf_2bd4f6f9901ebfdafca15b30dd52ee13 from "../assets/pasurams/2bd4f6f9901ebfdafca15b30dd52ee13.pdf";
import pdf_38987b84104a301e9ecfed87fcf00882 from "../assets/pasurams/38987b84104a301e9ecfed87fcf00882.pdf";
import pdf_49910d1f8529b8da5031bc6f7dc6b167 from "../assets/pasurams/49910d1f8529b8da5031bc6f7dc6b167.pdf";
import pdf_ee2eda4216510707eac4304a34cc41ff from "../assets/pasurams/ee2eda4216510707eac4304a34cc41ff.pdf";
import pdf_20a798bee7e50ccb41054c76a56d7805 from "../assets/pasurams/20a798bee7e50ccb41054c76a56d7805.pdf";
import pdf_107c56eacfed016349cb3996d9309177 from "../assets/pasurams/107c56eacfed016349cb3996d9309177.pdf";
import pdf_ea33c958f5b8b6d78bb3340247ae0052 from "../assets/pasurams/ea33c958f5b8b6d78bb3340247ae0052.pdf";
import pdf_9642f5b946bae81ffa02e465650ea490 from "../assets/pasurams/9642f5b946bae81ffa02e465650ea490.pdf";
import pdf_0950d5eb1b232b85697ea775ecd7c819 from "../assets/pasurams/0950d5eb1b232b85697ea775ecd7c819.pdf";
import pdf_ba616d544498fa9d08665e62a9ad7036 from "../assets/pasurams/ba616d544498fa9d08665e62a9ad7036.pdf";
import pdf_84749dd75d697ad6efcad6ec2c1a6a49 from "../assets/pasurams/84749dd75d697ad6efcad6ec2c1a6a49.pdf";
import pdf_082b09ca86cac5c9274bba5f1b63d01d from "../assets/pasurams/082b09ca86cac5c9274bba5f1b63d01d.pdf";
import pdf_24d018d790879553b79f5dd972bb9c6d from "../assets/pasurams/24d018d790879553b79f5dd972bb9c6d.pdf";
import pdf_d8de5ffda59b88b84258c972b2e5e94d from "../assets/pasurams/d8de5ffda59b88b84258c972b2e5e94d.pdf";
import pdf_001e17f7c50ba1d9c15e9447b00a46de from "../assets/pasurams/001e17f7c50ba1d9c15e9447b00a46de.pdf";
import pdf_00aecf37b8c162b54183470af23fa9ba from "../assets/pasurams/00aecf37b8c162b54183470af23fa9ba.pdf";
import pdf_1f2be7d5b2a6feb24dba25a931303ffc from "../assets/pasurams/1f2be7d5b2a6feb24dba25a931303ffc.pdf";
import pdf_39585b562b6f81d73b2dd7c9fc428bf4 from "../assets/pasurams/39585b562b6f81d73b2dd7c9fc428bf4.pdf";
import pdf_ce6531d6f7325a976bdd83886e764183 from "../assets/pasurams/ce6531d6f7325a976bdd83886e764183.pdf";
import pdf_98fc339d96ae1619d8795bcec83893f4 from "../assets/pasurams/98fc339d96ae1619d8795bcec83893f4.pdf";
import pdf_4502a4cdfc9c90725e110aa16b38012a from "../assets/pasurams/4502a4cdfc9c90725e110aa16b38012a.pdf";
import pdf_5d257b979b5658134f6015dafae4f6b1 from "../assets/pasurams/5d257b979b5658134f6015dafae4f6b1.pdf";
import pdf_69b39b1d78f147545a088f408da7271c from "../assets/pasurams/69b39b1d78f147545a088f408da7271c.pdf";
import pdf_77d56564227c6e19c3e270f9d6ea4eb2 from "../assets/pasurams/77d56564227c6e19c3e270f9d6ea4eb2.pdf";
import pdf_1a1102082d91cbeee55d1e3d8b3eab11 from "../assets/pasurams/1a1102082d91cbeee55d1e3d8b3eab11.pdf";
import pdf_14695f8d74ba6bb79720504572d77188 from "../assets/pasurams/14695f8d74ba6bb79720504572d77188.pdf";
import pdf_53a9c93dc065df39631bbdcce9a2a3b1 from "../assets/pasurams/53a9c93dc065df39631bbdcce9a2a3b1.pdf";
import pdf_8b188b4a44f7524b98b13486cb371ff7 from "../assets/pasurams/8b188b4a44f7524b98b13486cb371ff7.pdf";
import pdf_c7a1455e41c01e09b08fbf5063eab51a from "../assets/pasurams/c7a1455e41c01e09b08fbf5063eab51a.pdf";
import pdf_abc546d2fa89356b7e4e5a09417fa600 from "../assets/pasurams/abc546d2fa89356b7e4e5a09417fa600.pdf";
import pdf_77d503a7b71a4e8612180b7c10dec75c from "../assets/pasurams/77d503a7b71a4e8612180b7c10dec75c.pdf";
import pdf_3eb754d53398d057919e451979189d8b from "../assets/pasurams/3eb754d53398d057919e451979189d8b.pdf";
import pdf_cc77b3f234526c6486e5a99cacbb1f26 from "../assets/pasurams/cc77b3f234526c6486e5a99cacbb1f26.pdf";
import pdf_89b07799702a64e1b8747f618d4ffba5 from "../assets/pasurams/89b07799702a64e1b8747f618d4ffba5.pdf";
import pdf_98c8ba56001cb19203fa5bb25b958291 from "../assets/pasurams/98c8ba56001cb19203fa5bb25b958291.pdf";
import pdf_bf882f4dbda1fc98d8a7326804cd0c89 from "../assets/pasurams/bf882f4dbda1fc98d8a7326804cd0c89.pdf";
import pdf_a62f7c78c39dfc91d32962518c11e98b from "../assets/pasurams/a62f7c78c39dfc91d32962518c11e98b.pdf";
import pdf_4d988c41b9e4108f07baec532c53fce8 from "../assets/pasurams/4d988c41b9e4108f07baec532c53fce8.pdf";
import pdf_8b7c2687f813f20888cda8abbff8031f from "../assets/pasurams/8b7c2687f813f20888cda8abbff8031f.pdf";
import pdf_de63368c2964274ca2fce085016f5752 from "../assets/pasurams/de63368c2964274ca2fce085016f5752.pdf";
import pdf_2b4a2c7f1b2dd53976ae0f73a3371744 from "../assets/pasurams/2b4a2c7f1b2dd53976ae0f73a3371744.pdf";
import pdf_a5846b1bf78424f781394d4bde5b6fe4 from "../assets/pasurams/a5846b1bf78424f781394d4bde5b6fe4.pdf";
import pdf_09e563a35829c5f413b2bc47acd8ecd4 from "../assets/pasurams/09e563a35829c5f413b2bc47acd8ecd4.pdf";
import pdf_74c07df2dedb537171ea7142aed10810 from "../assets/pasurams/74c07df2dedb537171ea7142aed10810.pdf";
import pdf_0c885ee053b6a80336c1b9b9098a078b from "../assets/pasurams/0c885ee053b6a80336c1b9b9098a078b.pdf";
import pdf_4e03e6f8624a87b685d62557ca47fb5a from "../assets/pasurams/4e03e6f8624a87b685d62557ca47fb5a.pdf";
import pdf_d971a13cf1c2287596e6264bac051bb4 from "../assets/pasurams/d971a13cf1c2287596e6264bac051bb4.pdf";
import pdf_e76da10c76c75d99a67fa979fb3966a5 from "../assets/pasurams/e76da10c76c75d99a67fa979fb3966a5.pdf";
import pdf_1b1042ebf6493f28360725c091bf5d5b from "../assets/pasurams/1b1042ebf6493f28360725c091bf5d5b.pdf";
import pdf_85e73e8a01169b0152a476fd1e34c873 from "../assets/pasurams/85e73e8a01169b0152a476fd1e34c873.pdf";
import pdf_a2309545e516a72dbb010c88d7f30832 from "../assets/pasurams/a2309545e516a72dbb010c88d7f30832.pdf";
import pdf_3564617925a41ebc22b983fce69ca43a from "../assets/pasurams/3564617925a41ebc22b983fce69ca43a.pdf";
import pdf_26c683d546a4ca5f6466e71f556dfaa9 from "../assets/pasurams/26c683d546a4ca5f6466e71f556dfaa9.pdf";
import pdf_94ccabb6d89373840c0084edd51cef14 from "../assets/pasurams/94ccabb6d89373840c0084edd51cef14.pdf";
import pdf_2ed3501d28fbfefb0da7c341a240fdee from "../assets/pasurams/2ed3501d28fbfefb0da7c341a240fdee.pdf";
import pdf_8bb3ccd6383ef78c16738f5923fa88f2 from "../assets/pasurams/8bb3ccd6383ef78c16738f5923fa88f2.pdf";
import pdf_45783e32ef6ae0ff676855685808e910 from "../assets/pasurams/45783e32ef6ae0ff676855685808e910.pdf";
import pdf_30c693c78ce1c1275319e1db7c962c56 from "../assets/pasurams/30c693c78ce1c1275319e1db7c962c56.pdf";
import pdf_7fb695672d8c222a6460500e9a0a885b from "../assets/pasurams/7fb695672d8c222a6460500e9a0a885b.pdf";
import pdf_c49584e64827a9f2534cb12f5abc1228 from "../assets/pasurams/c49584e64827a9f2534cb12f5abc1228.pdf";
import pdf_38d93c44bb560755f7ec276d3bf6c612 from "../assets/pasurams/38d93c44bb560755f7ec276d3bf6c612.pdf";
import pdf_a9641f675daf9305059c1799c2d6d3cd from "../assets/pasurams/a9641f675daf9305059c1799c2d6d3cd.pdf";
import pdf_098ebe89bd6606aa168d5a7048860898 from "../assets/pasurams/098ebe89bd6606aa168d5a7048860898.pdf";
import pdf_ae744dfb8bec79908d85d3a0e5ca62fb from "../assets/pasurams/ae744dfb8bec79908d85d3a0e5ca62fb.pdf";
import pdf_0e6d679a1e1d55fc59f0812a06278df5 from "../assets/pasurams/0e6d679a1e1d55fc59f0812a06278df5.pdf";
import pdf_ad6fafaefc1e1d09461c8b2ca431460d from "../assets/pasurams/ad6fafaefc1e1d09461c8b2ca431460d.pdf";
import pdf_83c5ecf85f335bacbf3c757c705bc675 from "../assets/pasurams/83c5ecf85f335bacbf3c757c705bc675.pdf";
import pdf_a7fe82c11c78825dad655380bd8a4c5c from "../assets/pasurams/a7fe82c11c78825dad655380bd8a4c5c.pdf";
import pdf_3093a5770b568a8c3a10e8b5b1925aa8 from "../assets/pasurams/3093a5770b568a8c3a10e8b5b1925aa8.pdf";
import pdf_749242df1cd0e9d508d508b000df648c from "../assets/pasurams/749242df1cd0e9d508d508b000df648c.pdf";
import pdf_ce3bb0b65e7c860deac387fccb90850f from "../assets/pasurams/ce3bb0b65e7c860deac387fccb90850f.pdf";
import pdf_7342d2af1077f4af7a6abd21b291035c from "../assets/pasurams/7342d2af1077f4af7a6abd21b291035c.pdf";
import pdf_41ff6f93cd043bfc0ef0159d16b39172 from "../assets/pasurams/41ff6f93cd043bfc0ef0159d16b39172.pdf";
import pdf_2abc8a7f6d321fa7da6ce9cb75857256 from "../assets/pasurams/2abc8a7f6d321fa7da6ce9cb75857256.pdf";
import pdf_4e49e389d706a5c26d149aa7612882c4 from "../assets/pasurams/4e49e389d706a5c26d149aa7612882c4.pdf";
import pdf_1f9f8d30b305cd9d230c15b0719fd1f1 from "../assets/pasurams/1f9f8d30b305cd9d230c15b0719fd1f1.pdf";
import pdf_13255b159caf5f544e8e142caa68ad06 from "../assets/pasurams/13255b159caf5f544e8e142caa68ad06.pdf";
import pdf_42f79bab7a414379d96834d78d797fff from "../assets/pasurams/42f79bab7a414379d96834d78d797fff.pdf";
import pdf_60a26488beab6c598f633916abe0813b from "../assets/pasurams/60a26488beab6c598f633916abe0813b.pdf";
import pdf_ed42eda4fc0538c98d52e5565207c9b4 from "../assets/pasurams/ed42eda4fc0538c98d52e5565207c9b4.pdf";
import pdf_75667f3535c8e2b5211bd674fffbd9cc from "../assets/pasurams/75667f3535c8e2b5211bd674fffbd9cc.pdf";
import pdf_013dd9d87ebfdf3db2cd98d32db5fd32 from "../assets/pasurams/013dd9d87ebfdf3db2cd98d32db5fd32.pdf";
import pdf_e73af7e7b4d0cf221d3cc5b1a929f146 from "../assets/pasurams/e73af7e7b4d0cf221d3cc5b1a929f146.pdf";
import pdf_41861656e8d129ebd8fe3b424bf755e3 from "../assets/pasurams/41861656e8d129ebd8fe3b424bf755e3.pdf";
import pdf_7645310d908c6c5b000cf9cd4cadb87c from "../assets/pasurams/7645310d908c6c5b000cf9cd4cadb87c.pdf";
import pdf_45f498e670be36354e0bb057c5e0981a from "../assets/pasurams/45f498e670be36354e0bb057c5e0981a.pdf";
import pdf_2a924982e803d689b9b5c97bc9313962 from "../assets/pasurams/2a924982e803d689b9b5c97bc9313962.pdf";
import pdf_4035421d77b134a15f3b27b57b2945d4 from "../assets/pasurams/4035421d77b134a15f3b27b57b2945d4.pdf";
import pdf_12287bccb75d133e9486c9878ff44c2d from "../assets/pasurams/12287bccb75d133e9486c9878ff44c2d.pdf";
import pdf_a554296e6d520e369fd411fa399c641e from "../assets/pasurams/a554296e6d520e369fd411fa399c641e.pdf";
import pdf_a87080ed690db8d40a7198f8a80b571c from "../assets/pasurams/a87080ed690db8d40a7198f8a80b571c.pdf";
import pdf_71a34d41c83c85920ae2753d948230ff from "../assets/pasurams/71a34d41c83c85920ae2753d948230ff.pdf";
import pdf_b8dac491c4ddbac02a79ba2a6037e025 from "../assets/pasurams/b8dac491c4ddbac02a79ba2a6037e025.pdf";
import pdf_6f110113a6b1db916855804167aa8665 from "../assets/pasurams/6f110113a6b1db916855804167aa8665.pdf";
import pdf_ab6a91aaf69ecde2d19eaba806a60a4b from "../assets/pasurams/ab6a91aaf69ecde2d19eaba806a60a4b.pdf";
import pdf_6e1d76207b7531acb4aa5f348c347497 from "../assets/pasurams/6e1d76207b7531acb4aa5f348c347497.pdf";
import pdf_83fe0594ecfeecf3dcc3cd497027d429 from "../assets/pasurams/83fe0594ecfeecf3dcc3cd497027d429.pdf";
import pdf_ffb48e24472cddacd636cb8d522cfa2b from "../assets/pasurams/ffb48e24472cddacd636cb8d522cfa2b.pdf";
import pdf_d5968115f4ff0470d30df2f2cc386972 from "../assets/pasurams/d5968115f4ff0470d30df2f2cc386972.pdf";
import pdf_ddaeced0756d392db1f4b4881bf4331e from "../assets/pasurams/ddaeced0756d392db1f4b4881bf4331e.pdf";
import pdf_418e60abd5df4a53730c33353850ecc1 from "../assets/pasurams/418e60abd5df4a53730c33353850ecc1.pdf";
import pdf_a5f1def787c9f8aa110dcfcf4744a10b from "../assets/pasurams/a5f1def787c9f8aa110dcfcf4744a10b.pdf";
import pdf_a59f91898b79c2358ac7d09c9fdd7316 from "../assets/pasurams/a59f91898b79c2358ac7d09c9fdd7316.pdf";
import pdf_29cab62cfd249286cca2d95465d5ee0c from "../assets/pasurams/29cab62cfd249286cca2d95465d5ee0c.pdf";
import pdf_371ba8522e050d5fc8c2128b39f086a0 from "../assets/pasurams/371ba8522e050d5fc8c2128b39f086a0.pdf";
import pdf_be6b712869b41d4421bbe3a5b4bdc3eb from "../assets/pasurams/be6b712869b41d4421bbe3a5b4bdc3eb.pdf";
import pdf_7588328853d7956717620c1b3177cfee from "../assets/pasurams/7588328853d7956717620c1b3177cfee.pdf";
import pdf_656d542f000e5c04556208d1db430457 from "../assets/pasurams/656d542f000e5c04556208d1db430457.pdf";
import pdf_665e60087915483bd471c81874b1619a from "../assets/pasurams/665e60087915483bd471c81874b1619a.pdf";
import pdf_e1a11211ac0305dab30a27d85b8c9b61 from "../assets/pasurams/e1a11211ac0305dab30a27d85b8c9b61.pdf";
import pdf_ab27f9a0f094a57658089b29e6a041ee from "../assets/pasurams/ab27f9a0f094a57658089b29e6a041ee.pdf";
import pdf_f22f9ad75b01ec9a13b567099aec191d from "../assets/pasurams/f22f9ad75b01ec9a13b567099aec191d.pdf";
import pdf_68efe14e656c2cc55624e3551d1ffdf9 from "../assets/pasurams/68efe14e656c2cc55624e3551d1ffdf9.pdf";
import pdf_de7a1586932d7ff1aa67fbb67b98d9a8 from "../assets/pasurams/de7a1586932d7ff1aa67fbb67b98d9a8.pdf";
import pdf_4ba21f8eb693ed89d6cf47fc9969a86c from "../assets/pasurams/4ba21f8eb693ed89d6cf47fc9969a86c.pdf";
import pdf_e5c2aca1bb72e5c709d3de776a92660a from "../assets/pasurams/e5c2aca1bb72e5c709d3de776a92660a.pdf";
import pdf_84dc278992f326039491d25eedcf9f41 from "../assets/pasurams/84dc278992f326039491d25eedcf9f41.pdf";
import pdf_f6797c85a1e11b00fe73cad6f801292b from "../assets/pasurams/f6797c85a1e11b00fe73cad6f801292b.pdf";
import pdf_e7edfa7feeadad11658e7274e0090999 from "../assets/pasurams/e7edfa7feeadad11658e7274e0090999.pdf";
import pdf_1b61b8c1baaa414f20d2ffebb2d66454 from "../assets/pasurams/1b61b8c1baaa414f20d2ffebb2d66454.pdf";
import pdf_77ccfee78ee04b558696afec3a017e17 from "../assets/pasurams/77ccfee78ee04b558696afec3a017e17.pdf";
import pdf_4eb0df285963fe7fcfce6dc350751b11 from "../assets/pasurams/4eb0df285963fe7fcfce6dc350751b11.pdf";
import pdf_8f43dcfe3951ad5ef52e14d477c50ff9 from "../assets/pasurams/8f43dcfe3951ad5ef52e14d477c50ff9.pdf";
import pdf_07ad26f570223877a5601f51c48a33a0 from "../assets/pasurams/07ad26f570223877a5601f51c48a33a0.pdf";
import pdf_f0ca3253790fb56440290d9d27980a52 from "../assets/pasurams/f0ca3253790fb56440290d9d27980a52.pdf";
import pdf_bc1072303859f6884a4cefc3ce132530 from "../assets/pasurams/bc1072303859f6884a4cefc3ce132530.pdf";
import pdf_8900a941d37e5a5488b9c8a51293892c from "../assets/pasurams/8900a941d37e5a5488b9c8a51293892c.pdf";
import pdf_eab488407cef44157a6fbfeb71abf7da from "../assets/pasurams/eab488407cef44157a6fbfeb71abf7da.pdf";
import pdf_f4e1c51281aa850e083bdb47117f41ff from "../assets/pasurams/f4e1c51281aa850e083bdb47117f41ff.pdf";
import pdf_c6fac6267eb38c0ac27e8696902943d9 from "../assets/pasurams/c6fac6267eb38c0ac27e8696902943d9.pdf";
import pdf_59442ea8c718ddcce6e0b620358fe766 from "../assets/pasurams/59442ea8c718ddcce6e0b620358fe766.pdf";
import pdf_ceedf02e1b1594d1b9dfe835f423001a from "../assets/pasurams/ceedf02e1b1594d1b9dfe835f423001a.pdf";
import pdf_21047c84fc00295b8bdea3b4d22f5b7c from "../assets/pasurams/21047c84fc00295b8bdea3b4d22f5b7c.pdf";
import pdf_3bae2b70bfb3d855082258991f742596 from "../assets/pasurams/3bae2b70bfb3d855082258991f742596.pdf";
import pdf_141cd67ac2ed7d0a2583dd8145445bfb from "../assets/pasurams/141cd67ac2ed7d0a2583dd8145445bfb.pdf";
import pdf_3f054532f80552a0ee1665a55d658a27 from "../assets/pasurams/3f054532f80552a0ee1665a55d658a27.pdf";
import pdf_76c382549d741dc47d9be70a22bea01a from "../assets/pasurams/76c382549d741dc47d9be70a22bea01a.pdf";
import pdf_d9732d86c7ff689d451f92c6b6eda0fd from "../assets/pasurams/d9732d86c7ff689d451f92c6b6eda0fd.pdf";
import pdf_21a568f413c05da84fef4896a9be126e from "../assets/pasurams/21a568f413c05da84fef4896a9be126e.pdf";
import pdf_1ff275d0e0499595fbf01acf0d008a44 from "../assets/pasurams/1ff275d0e0499595fbf01acf0d008a44.pdf";
import pdf_034acea95332193cfa44dbf9f34daa66 from "../assets/pasurams/034acea95332193cfa44dbf9f34daa66.pdf";
import pdf_bbee840345175eed9b15a0b7e148e243 from "../assets/pasurams/bbee840345175eed9b15a0b7e148e243.pdf";
import pdf_36864ac55aca0a1b124f59268edbc8b2 from "../assets/pasurams/36864ac55aca0a1b124f59268edbc8b2.pdf";
import pdf_7c519ed12ff5b1df53e93c421e79b6aa from "../assets/pasurams/7c519ed12ff5b1df53e93c421e79b6aa.pdf";
import pdf_8370de95c174cc7e95533d393d7e2e2b from "../assets/pasurams/8370de95c174cc7e95533d393d7e2e2b.pdf";
import pdf_f00e5d0ecedfb380a1dfde244d0a89ff from "../assets/pasurams/f00e5d0ecedfb380a1dfde244d0a89ff.pdf";
import pdf_0c7ded7a180b848a63d7effe04bc947d from "../assets/pasurams/0c7ded7a180b848a63d7effe04bc947d.pdf";
import pdf_b7b25dde6a80289bfe3068984800d3a5 from "../assets/pasurams/b7b25dde6a80289bfe3068984800d3a5.pdf";
import pdf_6fbed6c210e2c6f84cae188cf0650c85 from "../assets/pasurams/6fbed6c210e2c6f84cae188cf0650c85.pdf";
import pdf_17c0df6f37604372b03435df65219a0a from "../assets/pasurams/17c0df6f37604372b03435df65219a0a.pdf";
import pdf_cb00e69a9ee69c5027657c4b90ca4ea9 from "../assets/pasurams/cb00e69a9ee69c5027657c4b90ca4ea9.pdf";
import pdf_197e87f905003d5a67174b57f426b70b from "../assets/pasurams/197e87f905003d5a67174b57f426b70b.pdf";
import pdf_f81ab458325f02f6c3f09968f0d2efef from "../assets/pasurams/f81ab458325f02f6c3f09968f0d2efef.pdf";
import pdf_8c93dd300629028444b26b16c2144692 from "../assets/pasurams/8c93dd300629028444b26b16c2144692.pdf";
import pdf_c73a72dfe0a1acf1d6e11dd19ce0e146 from "../assets/pasurams/c73a72dfe0a1acf1d6e11dd19ce0e146.pdf";
import pdf_a9b9d9882c21bb6cf231c2ed30145929 from "../assets/pasurams/a9b9d9882c21bb6cf231c2ed30145929.pdf";
import pdf_dd3031e68763e67372fc87deb7b1d107 from "../assets/pasurams/dd3031e68763e67372fc87deb7b1d107.pdf";
import pdf_38d6f3c950432cce1cef27bf066cc555 from "../assets/pasurams/38d6f3c950432cce1cef27bf066cc555.pdf";
import pdf_0f24441b5bda00d0e57c44249925a49f from "../assets/pasurams/0f24441b5bda00d0e57c44249925a49f.pdf";
import pdf_7de977ead6ed0f27ad79bf3f1f3ff34f from "../assets/pasurams/7de977ead6ed0f27ad79bf3f1f3ff34f.pdf";
import pdf_c8b60f44e9c3ae4b10452220902a912d from "../assets/pasurams/c8b60f44e9c3ae4b10452220902a912d.pdf";
import pdf_84c3fc1a212ac41dc3de050fc335f67f from "../assets/pasurams/84c3fc1a212ac41dc3de050fc335f67f.pdf";
import pdf_0860a5ee5d123e41be6ee6730f78d4fe from "../assets/pasurams/0860a5ee5d123e41be6ee6730f78d4fe.pdf";
import pdf_c2c760e76a5a24d62a6d70c6148726cf from "../assets/pasurams/c2c760e76a5a24d62a6d70c6148726cf.pdf";
import pdf_f97efac654e92436771fc805fdf36fa9 from "../assets/pasurams/f97efac654e92436771fc805fdf36fa9.pdf";
import pdf_49db4a044d00b4c819d9c233117daade from "../assets/pasurams/49db4a044d00b4c819d9c233117daade.pdf";
import pdf_df099b0d1386901d4e2af91dd85d597b from "../assets/pasurams/df099b0d1386901d4e2af91dd85d597b.pdf";
import pdf_2a2b2cecc20a80e3572dbcc77a07b415 from "../assets/pasurams/2a2b2cecc20a80e3572dbcc77a07b415.pdf";
import pdf_117d10430465877211dce73ca16cb268 from "../assets/pasurams/117d10430465877211dce73ca16cb268.pdf";
import pdf_c032b3c714b063f27d4e0392beab26d4 from "../assets/pasurams/c032b3c714b063f27d4e0392beab26d4.pdf";
import pdf_299e9f20bdda4f2d6704550037b2a07b from "../assets/pasurams/299e9f20bdda4f2d6704550037b2a07b.pdf";
import pdf_0b36554728d9ad045b446704d6deb372 from "../assets/pasurams/0b36554728d9ad045b446704d6deb372.pdf";
import pdf_2c9f8afbbcb0beb22e1d84313c36df95 from "../assets/pasurams/2c9f8afbbcb0beb22e1d84313c36df95.pdf";
import pdf_952a2a6956887f840fc58ce0fa04f28c from "../assets/pasurams/952a2a6956887f840fc58ce0fa04f28c.pdf";
import pdf_2640138c4e49591ed99ad2292057f4f5 from "../assets/pasurams/2640138c4e49591ed99ad2292057f4f5.pdf";
import pdf_eafdf6a3ca66e33e75a114ffdefe0855 from "../assets/pasurams/eafdf6a3ca66e33e75a114ffdefe0855.pdf";
import pdf_d74b834e873f7d76d55fd1b991d70d1b from "../assets/pasurams/d74b834e873f7d76d55fd1b991d70d1b.pdf";
import pdf_0c14cec62fbba559427257a1f90ba372 from "../assets/pasurams/0c14cec62fbba559427257a1f90ba372.pdf";
import pdf_da976f5b4ff7da23e78f079af1ddc85b from "../assets/pasurams/da976f5b4ff7da23e78f079af1ddc85b.pdf";
import pdf_53cc8d90c0c2a98c11550c567ff43b01 from "../assets/pasurams/53cc8d90c0c2a98c11550c567ff43b01.pdf";
import pdf_2a8cef0bb0454d301112d16d9efa92e5 from "../assets/pasurams/2a8cef0bb0454d301112d16d9efa92e5.pdf";
import pdf_8613457a948e834ebff3739ea5a1e113 from "../assets/pasurams/8613457a948e834ebff3739ea5a1e113.pdf";
import pdf_de6bb208d838f5dfd5a86e0c056f4dd6 from "../assets/pasurams/de6bb208d838f5dfd5a86e0c056f4dd6.pdf";
import pdf_0518ec4a2bde5988bc0ac91095416223 from "../assets/pasurams/0518ec4a2bde5988bc0ac91095416223.pdf";
import pdf_fe42f7ebd4f56af5f506f3d77be3233f from "../assets/pasurams/fe42f7ebd4f56af5f506f3d77be3233f.pdf";
import pdf_1d4c49d8d9c0681c060660406acd5979 from "../assets/pasurams/1d4c49d8d9c0681c060660406acd5979.pdf";
import pdf_f64cb7edf42094ebb4ca60da940bf0a9 from "../assets/pasurams/f64cb7edf42094ebb4ca60da940bf0a9.pdf";
import pdf_e925fe71bcc2648c5cfa82d17fd16959 from "../assets/pasurams/e925fe71bcc2648c5cfa82d17fd16959.pdf";
import pdf_515dbb073a2ef7addd267357bde5b0de from "../assets/pasurams/515dbb073a2ef7addd267357bde5b0de.pdf";
import pdf_d415b79673b64a9700e75a92315bed3b from "../assets/pasurams/d415b79673b64a9700e75a92315bed3b.pdf";
import pdf_d91883239caf106bd38b029b56d37b25 from "../assets/pasurams/d91883239caf106bd38b029b56d37b25.pdf";
import pdf_9ac625846802113082b73d5d6b7122e4 from "../assets/pasurams/9ac625846802113082b73d5d6b7122e4.pdf";
import pdf_0e4b2addb7266ebb729060d820b7ac0e from "../assets/pasurams/0e4b2addb7266ebb729060d820b7ac0e.pdf";
import pdf_8f7adfe35af3e2ae271addc7d60a6263 from "../assets/pasurams/8f7adfe35af3e2ae271addc7d60a6263.pdf";
import pdf_193bca96df35d7c6966fc26e46226ee2 from "../assets/pasurams/193bca96df35d7c6966fc26e46226ee2.pdf";
import pdf_10b9839c72dec2b6257c3d83b0b54e5e from "../assets/pasurams/10b9839c72dec2b6257c3d83b0b54e5e.pdf";
import pdf_e5f384c1f617f9e06e11e886acfdfb92 from "../assets/pasurams/e5f384c1f617f9e06e11e886acfdfb92.pdf";
import pdf_7dbb4d842436bd664895ad69a5140c9b from "../assets/pasurams/7dbb4d842436bd664895ad69a5140c9b.pdf";
import pdf_b1448c6194802eea6c4608bdb6ca4d59 from "../assets/pasurams/b1448c6194802eea6c4608bdb6ca4d59.pdf";
import pdf_442c0198d51141a68137614ccd5951ba from "../assets/pasurams/442c0198d51141a68137614ccd5951ba.pdf";
import pdf_70003b24276b7236ba1eeb501755b774 from "../assets/pasurams/70003b24276b7236ba1eeb501755b774.pdf";
import pdf_6dfdf2b33193820cb2e679cb196c8808 from "../assets/pasurams/6dfdf2b33193820cb2e679cb196c8808.pdf";
import pdf_216a925d4828aba34c29c9b3311f438d from "../assets/pasurams/216a925d4828aba34c29c9b3311f438d.pdf";
import pdf_806f334afd9247a7f6dcbb050caddbc2 from "../assets/pasurams/806f334afd9247a7f6dcbb050caddbc2.pdf";
import pdf_dfb9ff72c974cd705c7c95a75ccdff8f from "../assets/pasurams/dfb9ff72c974cd705c7c95a75ccdff8f.pdf";
import pdf_cbcd6e82328dd8123047c76f0ea18f97 from "../assets/pasurams/cbcd6e82328dd8123047c76f0ea18f97.pdf";
import pdf_1895f6554a0c5b93bdf4423b69d09b9a from "../assets/pasurams/1895f6554a0c5b93bdf4423b69d09b9a.pdf";
import pdf_c8b6e95f750c0b0a090f9a33c029a8eb from "../assets/pasurams/c8b6e95f750c0b0a090f9a33c029a8eb.pdf";
import pdf_253078ca26a2226235b4cee81da4a4b4 from "../assets/pasurams/253078ca26a2226235b4cee81da4a4b4.pdf";
import pdf_3c2410a55122b91cee3fc3fa874e15fe from "../assets/pasurams/3c2410a55122b91cee3fc3fa874e15fe.pdf";
import pdf_a8ce2970b68bd8ff5127236fcd82f9fb from "../assets/pasurams/a8ce2970b68bd8ff5127236fcd82f9fb.pdf";
import pdf_44317740b2a4f78fb29b18836b4b1e32 from "../assets/pasurams/44317740b2a4f78fb29b18836b4b1e32.pdf";
import pdf_0eacfd9e656b2d3a7851467032315f03 from "../assets/pasurams/0eacfd9e656b2d3a7851467032315f03.pdf";
import pdf_df8dd9f8510ae6d74e327ebc6c789378 from "../assets/pasurams/df8dd9f8510ae6d74e327ebc6c789378.pdf";
import pdf_98da025671f595afe9dbcc3ffff3f3e9 from "../assets/pasurams/98da025671f595afe9dbcc3ffff3f3e9.pdf";
import pdf_34e6a75d39d9b414062d7e3f7aefbe9b from "../assets/pasurams/34e6a75d39d9b414062d7e3f7aefbe9b.pdf";
import pdf_cf42d45b14848d59aea477b27e29276a from "../assets/pasurams/cf42d45b14848d59aea477b27e29276a.pdf";
import pdf_42dbd71c29790101561beb9092fd3fe1 from "../assets/pasurams/42dbd71c29790101561beb9092fd3fe1.pdf";
import pdf_a09fb087b98e330bf86358927f3b1c41 from "../assets/pasurams/a09fb087b98e330bf86358927f3b1c41.pdf";
import pdf_9bd3d433a82e79004e395409fe21de5c from "../assets/pasurams/9bd3d433a82e79004e395409fe21de5c.pdf";
import pdf_e229a3bd8ab6a2414caae7855a26d5c9 from "../assets/pasurams/e229a3bd8ab6a2414caae7855a26d5c9.pdf";
import pdf_5049973c54b103f0969dc9a8934b1d29 from "../assets/pasurams/5049973c54b103f0969dc9a8934b1d29.pdf";
import pdf_6b8fa3c60a0fc1c8b0cfa2f9de2f18a0 from "../assets/pasurams/6b8fa3c60a0fc1c8b0cfa2f9de2f18a0.pdf";
import pdf_a65df048140e685a937d2e1644ebf9db from "../assets/pasurams/a65df048140e685a937d2e1644ebf9db.pdf";
import pdf_14a641ffd27b02d79ae329c5ac5e82eb from "../assets/pasurams/14a641ffd27b02d79ae329c5ac5e82eb.pdf";
import pdf_ff3811ee99dfe6e076eeffee81cd85db from "../assets/pasurams/ff3811ee99dfe6e076eeffee81cd85db.pdf";
import pdf_a71825ffe35310bcefd6c3edad884e21 from "../assets/pasurams/a71825ffe35310bcefd6c3edad884e21.pdf";
import pdf_07e2de65c1cf1e3def591f6184e5bdbf from "../assets/pasurams/07e2de65c1cf1e3def591f6184e5bdbf.pdf";
import pdf_594440a2f1d55d2b47ccfcfe3808e781 from "../assets/pasurams/594440a2f1d55d2b47ccfcfe3808e781.pdf";
import pdf_6c1b76c32b2f75a9a572e1678860b6f2 from "../assets/pasurams/6c1b76c32b2f75a9a572e1678860b6f2.pdf";
import pdf_973c9239f43d2ca5d105542b86a3e7c3 from "../assets/pasurams/973c9239f43d2ca5d105542b86a3e7c3.pdf";
import pdf_0d1c8c67946f32def406c096f0db1493 from "../assets/pasurams/0d1c8c67946f32def406c096f0db1493.pdf";
import pdf_c2da880957dab0f800bfb3ace5e2a673 from "../assets/pasurams/c2da880957dab0f800bfb3ace5e2a673.pdf";
import pdf_51dc9208b5b46f837599c0384ab29e0a from "../assets/pasurams/51dc9208b5b46f837599c0384ab29e0a.pdf";
import pdf_a34cc35c3cd289a937b00f319079eae1 from "../assets/pasurams/a34cc35c3cd289a937b00f319079eae1.pdf";
import pdf_a6ce697ab758562181cd6256fb3f8abf from "../assets/pasurams/a6ce697ab758562181cd6256fb3f8abf.pdf";
import pdf_559e4652faba9025b14825682281aca8 from "../assets/pasurams/559e4652faba9025b14825682281aca8.pdf";
import pdf_b6388d68fa99c96eb84610c6974436dc from "../assets/pasurams/b6388d68fa99c96eb84610c6974436dc.pdf";
import pdf_1c0d4b032ff1bd6a9c2aa7e71e95088e from "../assets/pasurams/1c0d4b032ff1bd6a9c2aa7e71e95088e.pdf";
import pdf_511c56741841944c240656364a3e5755 from "../assets/pasurams/511c56741841944c240656364a3e5755.pdf";
import pdf_9c4888a40e6d7f82d642b04ffb6bb6a3 from "../assets/pasurams/9c4888a40e6d7f82d642b04ffb6bb6a3.pdf";
import pdf_674b69642085592b18d65d67d65155fc from "../assets/pasurams/674b69642085592b18d65d67d65155fc.pdf";
import pdf_bea57131380e0127f53d58c93ba4a362 from "../assets/pasurams/bea57131380e0127f53d58c93ba4a362.pdf";
import pdf_3475e2c8876e9f81ad48975160c5c4e4 from "../assets/pasurams/3475e2c8876e9f81ad48975160c5c4e4.pdf";
import pdf_937e7fa2e9487e02fa69f216fa5d17c2 from "../assets/pasurams/937e7fa2e9487e02fa69f216fa5d17c2.pdf";
import pdf_e7e8a2bb9c7a317fa0be8d74d3f44684 from "../assets/pasurams/e7e8a2bb9c7a317fa0be8d74d3f44684.pdf";
import pdf_570aa3e81d8d02c5a3dc883e4c5e6739 from "../assets/pasurams/570aa3e81d8d02c5a3dc883e4c5e6739.pdf";
import pdf_e22ab3a960795caa8f472c95f1d7e5d3 from "../assets/pasurams/e22ab3a960795caa8f472c95f1d7e5d3.pdf";
import pdf_1fc15dc30e1eb2b90fa760bc3646d1f0 from "../assets/pasurams/1fc15dc30e1eb2b90fa760bc3646d1f0.pdf";
import pdf_a573e27e70898aaafeba4b2bfb4336a9 from "../assets/pasurams/a573e27e70898aaafeba4b2bfb4336a9.pdf";
import pdf_d4962e9b5f024e588cb28f97530429e6 from "../assets/pasurams/d4962e9b5f024e588cb28f97530429e6.pdf";
import pdf_ddc2599bd44ec20c7eb9de076e65abaa from "../assets/pasurams/ddc2599bd44ec20c7eb9de076e65abaa.pdf";
import pdf_afca1ac5fed63986ee0def218dba7154 from "../assets/pasurams/afca1ac5fed63986ee0def218dba7154.pdf";
import pdf_13ffa4a4a8dd28c11b994caf3154d5a5 from "../assets/pasurams/13ffa4a4a8dd28c11b994caf3154d5a5.pdf";
import pdf_e33210d1603eb6931c1d357abb01a23f from "../assets/pasurams/e33210d1603eb6931c1d357abb01a23f.pdf";
import pdf_a7206c105aa23d94404aeaafe59720b6 from "../assets/pasurams/a7206c105aa23d94404aeaafe59720b6.pdf";
import pdf_2184f393e8888df83309ab52eec797d6 from "../assets/pasurams/2184f393e8888df83309ab52eec797d6.pdf";
import pdf_96a3749346b339333a353b8743044492 from "../assets/pasurams/96a3749346b339333a353b8743044492.pdf";
import pdf_2ee544cf0fd79487eb548cc4cbd6dc3f from "../assets/pasurams/2ee544cf0fd79487eb548cc4cbd6dc3f.pdf";
import pdf_147d5ec7c2884d418b082dffd2a33500 from "../assets/pasurams/147d5ec7c2884d418b082dffd2a33500.pdf";
import pdf_8c84b55c994bae6e3059cb8048df33f1 from "../assets/pasurams/8c84b55c994bae6e3059cb8048df33f1.pdf";
import pdf_5b4135b44fe275b7f845319f25e74999 from "../assets/pasurams/5b4135b44fe275b7f845319f25e74999.pdf";
import pdf_74437a9ab81898010c3ccb1e782d3142 from "../assets/pasurams/74437a9ab81898010c3ccb1e782d3142.pdf";
import pdf_a0144544249c4f64dbf649d8e9974e28 from "../assets/pasurams/a0144544249c4f64dbf649d8e9974e28.pdf";
import pdf_56968eb76429aa57006bc2090972650e from "../assets/pasurams/56968eb76429aa57006bc2090972650e.pdf";
import pdf_66d33cfe529ce0921efb82d8187d1bfb from "../assets/pasurams/66d33cfe529ce0921efb82d8187d1bfb.pdf";
import pdf_5de99fc3921db60d153e493f01a1c78c from "../assets/pasurams/5de99fc3921db60d153e493f01a1c78c.pdf";
import pdf_ea6ae09b6db0f952fda275c78e4a2a0b from "../assets/pasurams/ea6ae09b6db0f952fda275c78e4a2a0b.pdf";
import pdf_c117f24a02c439107d959df8b8063e2a from "../assets/pasurams/c117f24a02c439107d959df8b8063e2a.pdf";
import pdf_acfa9ff7abacc8e610d8ec8b958596f5 from "../assets/pasurams/acfa9ff7abacc8e610d8ec8b958596f5.pdf";
import pdf_4c92bb0ac189f607e00dd53f65e0b84d from "../assets/pasurams/4c92bb0ac189f607e00dd53f65e0b84d.pdf";
import pdf_af6ce22ac982da5701725249ab3ee5c8 from "../assets/pasurams/af6ce22ac982da5701725249ab3ee5c8.pdf";
import pdf_9de09b30131765866e6dab287ff57160 from "../assets/pasurams/9de09b30131765866e6dab287ff57160.pdf";
import pdf_f4de409bfdf951fdc6dafe50dc60e9aa from "../assets/pasurams/f4de409bfdf951fdc6dafe50dc60e9aa.pdf";
import pdf_6937dcf9bddd0f4fe51961374c331015 from "../assets/pasurams/6937dcf9bddd0f4fe51961374c331015.pdf";
import pdf_3c10c2111264057a1f6fe66af586f66b from "../assets/pasurams/3c10c2111264057a1f6fe66af586f66b.pdf";
import pdf_105fd65678c57ed5ac0648756096f357 from "../assets/pasurams/105fd65678c57ed5ac0648756096f357.pdf";
import pdf_9173f42e47e403739c064e4692a8abe3 from "../assets/pasurams/9173f42e47e403739c064e4692a8abe3.pdf";
import pdf_a997e3565417baeb54536d4c10ef24f3 from "../assets/pasurams/a997e3565417baeb54536d4c10ef24f3.pdf";
import pdf_0bc523451cbe5267fa5386780151e3f5 from "../assets/pasurams/0bc523451cbe5267fa5386780151e3f5.pdf";
import pdf_29e0acd157a05077c598e4a810886dd3 from "../assets/pasurams/29e0acd157a05077c598e4a810886dd3.pdf";
import pdf_6a34cfdfbe7f208065a07dd30a7310f8 from "../assets/pasurams/6a34cfdfbe7f208065a07dd30a7310f8.pdf";
import pdf_da7c451f44ed35a973df3423a3436231 from "../assets/pasurams/da7c451f44ed35a973df3423a3436231.pdf";
import pdf_89eb494aa52a58fe5d9ade25b2ba775f from "../assets/pasurams/89eb494aa52a58fe5d9ade25b2ba775f.pdf";
import pdf_ed755ea84744585276610b4c8e648280 from "../assets/pasurams/ed755ea84744585276610b4c8e648280.pdf";
import pdf_2b70618b1dacad5d02c88fc1a3343a07 from "../assets/pasurams/2b70618b1dacad5d02c88fc1a3343a07.pdf";
import pdf_29b8d5169261a83a8976f015d5aa837c from "../assets/pasurams/29b8d5169261a83a8976f015d5aa837c.pdf";
import pdf_7dae5e8abed1f28831fa0e0cf2cfcd05 from "../assets/pasurams/7dae5e8abed1f28831fa0e0cf2cfcd05.pdf";
import pdf_badf2b022fb7abe16dbdae024c13306b from "../assets/pasurams/badf2b022fb7abe16dbdae024c13306b.pdf";
import pdf_22fc863d0ec8a29b7f98c34fc2fad98c from "../assets/pasurams/22fc863d0ec8a29b7f98c34fc2fad98c.pdf";
import pdf_db57121a22dbc69abf310b056a27fa32 from "../assets/pasurams/db57121a22dbc69abf310b056a27fa32.pdf";
import pdf_404c659ca334b6512e7098b7d313e496 from "../assets/pasurams/404c659ca334b6512e7098b7d313e496.pdf";
import pdf_c887c84c1a7bd098265d0da72d1c7d67 from "../assets/pasurams/c887c84c1a7bd098265d0da72d1c7d67.pdf";
import pdf_aae92bfcb68b757c2210658e5db3e415 from "../assets/pasurams/aae92bfcb68b757c2210658e5db3e415.pdf";
import pdf_7a96d73dec9090888c8dfa00aedfe609 from "../assets/pasurams/7a96d73dec9090888c8dfa00aedfe609.pdf";
import pdf_7ee1af8a2242a4dc10473d9859012d12 from "../assets/pasurams/7ee1af8a2242a4dc10473d9859012d12.pdf";
import pdf_588858966b0ed6d3e417d19b720c07a3 from "../assets/pasurams/588858966b0ed6d3e417d19b720c07a3.pdf";
import pdf_a68a7087f910c8f92c511fd46b4ded65 from "../assets/pasurams/a68a7087f910c8f92c511fd46b4ded65.pdf";
import pdf_622a656f915f5c271d9b9219016d2db8 from "../assets/pasurams/622a656f915f5c271d9b9219016d2db8.pdf";
import pdf_15ff22556ddd3a59ab0f92a2a57a34c0 from "../assets/pasurams/15ff22556ddd3a59ab0f92a2a57a34c0.pdf";
import pdf_59418b7e2ec390d5760c381e0259a3a2 from "../assets/pasurams/59418b7e2ec390d5760c381e0259a3a2.pdf";
import pdf_bc16c690f1f36dbe5142df5c0f0c6955 from "../assets/pasurams/bc16c690f1f36dbe5142df5c0f0c6955.pdf";
import pdf_5a908a37ceb664ca260b277a9d7bf786 from "../assets/pasurams/5a908a37ceb664ca260b277a9d7bf786.pdf";
import pdf_8c2e4bcd6670b5696c256ddb5194950a from "../assets/pasurams/8c2e4bcd6670b5696c256ddb5194950a.pdf";
import pdf_73ea64db0d22141eca5c85fe26d78a2b from "../assets/pasurams/73ea64db0d22141eca5c85fe26d78a2b.pdf";
import pdf_2769c6f5942d2610757dc8db3b076c08 from "../assets/pasurams/2769c6f5942d2610757dc8db3b076c08.pdf";
import pdf_2143b9e6e4e17817dbb422abade4af10 from "../assets/pasurams/2143b9e6e4e17817dbb422abade4af10.pdf";
import pdf_63cd4d3bd80880910d85118f3386e881 from "../assets/pasurams/63cd4d3bd80880910d85118f3386e881.pdf";
import pdf_39d83999dd93ad120339ba34db20e016 from "../assets/pasurams/39d83999dd93ad120339ba34db20e016.pdf";
import pdf_9ce69f1b146efcf88ba9a7afbaf068f8 from "../assets/pasurams/9ce69f1b146efcf88ba9a7afbaf068f8.pdf";
import pdf_f3ec7d5b53d5a918ceb30c7edb3eb6df from "../assets/pasurams/f3ec7d5b53d5a918ceb30c7edb3eb6df.pdf";
import pdf_53ff0360737ae049bee0eb1edcd4a2bb from "../assets/pasurams/53ff0360737ae049bee0eb1edcd4a2bb.pdf";
import pdf_e9917d71252b9895517ea1db983cdb54 from "../assets/pasurams/e9917d71252b9895517ea1db983cdb54.pdf";
import pdf_50aa504d7947274dec53251f10162e7c from "../assets/pasurams/50aa504d7947274dec53251f10162e7c.pdf";
import pdf_e142ca0049cb6c27fe4a436f1410edf3 from "../assets/pasurams/e142ca0049cb6c27fe4a436f1410edf3.pdf";
import pdf_68a9d62e4fed82f5c0d86d3e1c6d979c from "../assets/pasurams/68a9d62e4fed82f5c0d86d3e1c6d979c.pdf";
import pdf_5ebc0cfecc15b133a17610674c1218ae from "../assets/pasurams/5ebc0cfecc15b133a17610674c1218ae.pdf";
import pdf_ad19400366e02050d489e5f1b76a5ce0 from "../assets/pasurams/ad19400366e02050d489e5f1b76a5ce0.pdf";
import pdf_d9b8ffc9ca025fd4553ea238f9e0fc7c from "../assets/pasurams/d9b8ffc9ca025fd4553ea238f9e0fc7c.pdf";
import pdf_fe6457f4e706f42edad3e044f4085d0d from "../assets/pasurams/fe6457f4e706f42edad3e044f4085d0d.pdf";
import pdf_0cd71410eae980af79d5fd07a2f6483b from "../assets/pasurams/0cd71410eae980af79d5fd07a2f6483b.pdf";
import pdf_17b974f76009c6786e5120fe9ebef8cd from "../assets/pasurams/17b974f76009c6786e5120fe9ebef8cd.pdf";
import pdf_a82e137acedde9e26f4ae1d603e2c360 from "../assets/pasurams/a82e137acedde9e26f4ae1d603e2c360.pdf";
import pdf_2d4acafce0490672a5426d35533d36b4 from "../assets/pasurams/2d4acafce0490672a5426d35533d36b4.pdf";
import pdf_c0463749eb870b7aaa019bb24661865f from "../assets/pasurams/c0463749eb870b7aaa019bb24661865f.pdf";
import pdf_c93ed8cdbdcc8fd7e8baec48a9a3f861 from "../assets/pasurams/c93ed8cdbdcc8fd7e8baec48a9a3f861.pdf";
import pdf_dac7b466cebe4c6db8bcfda3d558a060 from "../assets/pasurams/dac7b466cebe4c6db8bcfda3d558a060.pdf";
import pdf_c6e4b3479871e4028c9b6737bc4738c0 from "../assets/pasurams/c6e4b3479871e4028c9b6737bc4738c0.pdf";
import pdf_7ebb9f2adbd1ee821a72adb22b205377 from "../assets/pasurams/7ebb9f2adbd1ee821a72adb22b205377.pdf";
import pdf_19ceadc8c72c1eba78bf538994aafb73 from "../assets/pasurams/19ceadc8c72c1eba78bf538994aafb73.pdf";
import pdf_01bb416cc19b10ec62cd114b623f9440 from "../assets/pasurams/01bb416cc19b10ec62cd114b623f9440.pdf";
import pdf_48b4a50cec70c230c2aa662c016ba14f from "../assets/pasurams/48b4a50cec70c230c2aa662c016ba14f.pdf";
import pdf_71b6bef84f854b695150983f037e329f from "../assets/pasurams/71b6bef84f854b695150983f037e329f.pdf";
import pdf_ffa4ca4febcfcfa86cb17fa6ee5c6143 from "../assets/pasurams/ffa4ca4febcfcfa86cb17fa6ee5c6143.pdf";
import pdf_556036ba904756bbc3685ffbc21bf495 from "../assets/pasurams/556036ba904756bbc3685ffbc21bf495.pdf";
import pdf_010398f3f1d51b95dc12cb06bc17a417 from "../assets/pasurams/010398f3f1d51b95dc12cb06bc17a417.pdf";
import pdf_0bfa3fcb9bcd3e1af235604de08ab75a from "../assets/pasurams/0bfa3fcb9bcd3e1af235604de08ab75a.pdf";
import pdf_9f9ce71426811aca26bd023d2ad0a600 from "../assets/pasurams/9f9ce71426811aca26bd023d2ad0a600.pdf";
import pdf_a8af8bb3e166ba4d93884bc9df6ab63b from "../assets/pasurams/a8af8bb3e166ba4d93884bc9df6ab63b.pdf";
import pdf_aedd6f489aee7ccd50cc4fd74eba34fc from "../assets/pasurams/aedd6f489aee7ccd50cc4fd74eba34fc.pdf";
import pdf_f616b3ff094894e5af1028bfb41b8bb9 from "../assets/pasurams/f616b3ff094894e5af1028bfb41b8bb9.pdf";
import pdf_c0339bcd26ce2e3b12ab5a6967959e5a from "../assets/pasurams/c0339bcd26ce2e3b12ab5a6967959e5a.pdf";

/** Prapatti resource URL -> Metro-resolved bundled PDF asset. */
export const pasuramAssetByUrl: Record<string, number> = {
  "https://www.prapatti.com/slokas/sanskrit/tirukkavittalampaasurangal.pdf": pdf_467afa852da5e07b93b4bbaae6cd5b52,
  "https://www.prapatti.com/slokas/kannada/tirukkavittalampaasurangal.pdf": pdf_cea3165fd24b9126a8bcf98c53a87184,
  "https://www.prapatti.com/slokas/tamil/tirukkavittalampaasurangal.pdf": pdf_ccd7d82c1569e55f0a289f5b78afa515,
  "https://www.prapatti.com/slokas/english/tirukkavittalampaasurangal.pdf": pdf_31f515a698fe9bcc75990ed8f84388cb,
  "https://www.prapatti.com/slokas/english/tirunaraiyuurpaasurangal.pdf": pdf_b97f96b8ebe37e1ae3f30fdaa368596f,
  "https://www.prapatti.com/slokas/kannada/tirunaraiyuurpaasurangal.pdf": pdf_f1f15e06aaa87503c3fb69c32a1adfc8,
  "https://www.prapatti.com/slokas/sanskrit/tirunaraiyuurpaasurangal.pdf": pdf_9e9bd7d8ae1067e0d829363ae1bf0c03,
  "https://www.prapatti.com/slokas/tamil/tirunaraiyuurpaasurangal.pdf": pdf_41a71e076bfc27782f6118dab98eae3e,
  "https://www.prapatti.com/slokas/sanskrit/tiruccingavelkunrampaasurangal.pdf": pdf_514706885d7dfcdfd94531f93a3a9686,
  "https://www.prapatti.com/slokas/tamil/tiruccingavelkunrampaasurangal.pdf": pdf_ff62fa134bbb6e695dfeaeea724d5a8a,
  "https://www.prapatti.com/slokas/english/tiruccingavelkunrampaasurangal.pdf": pdf_54e51f6845f4bcabbecaf45c61caec3e,
  "https://www.prapatti.com/slokas/kannada/tiruccingavelkunrampaasurangal.pdf": pdf_addb54d96ac0a9baf0b3b010a5a10c98,
  "https://www.prapatti.com/slokas/english/tiruvarangampaasurangal.pdf": pdf_c123e72fb52e1b9d05723d76e730d124,
  "https://www.prapatti.com/slokas/kannada/tiruvarangampaasurangal.pdf": pdf_646144e15a346f04629d6ca837b02af0,
  "https://www.prapatti.com/slokas/tamil/tiruvarangampaasurangal.pdf": pdf_923d6d7ea8c6ef607354ae5c0e2c2c58,
  "https://www.prapatti.com/slokas/sanskrit/tiruvarangampaasurangal.pdf": pdf_9303a28c963dfef63d63293b0bf61c66,
  "https://www.prapatti.com/slokas/kannada/tiruvilliputtuurpaasurangal.pdf": pdf_91f8d2e5757790954aeea6d3e420c954,
  "https://www.prapatti.com/slokas/sanskrit/tiruvilliputtuurpaasurangal.pdf": pdf_b187de4d88f0060367f3569f033e0189,
  "https://www.prapatti.com/slokas/english/tiruvilliputtuurpaasurangal.pdf": pdf_6eb2008d5b6c551300367d1504d20d50,
  "https://www.prapatti.com/slokas/tamil/tiruvilliputtuurpaasurangal.pdf": pdf_2f33bbb970c38c8880c1a11619acbd79,
  "https://www.prapatti.com/slokas/english/tiruttalaiccanganaanmadiyampaasurangal.pdf": pdf_600d2b39d41344e480e3b7b524942e69,
  "https://www.prapatti.com/slokas/kannada/tiruttalaiccanganaanmadiyampaasurangal.pdf": pdf_124af85ee1918c8d63741e048d12ae7b,
  "https://www.prapatti.com/slokas/tamil/tiruttalaiccanganaanmadiyampaasurangal.pdf": pdf_b8e9c60fbdd19d1a56547228227ab54f,
  "https://www.prapatti.com/slokas/sanskrit/tiruttalaiccanganaanmadiyampaasurangal.pdf": pdf_8f4549dbc1b7b03e6779170cf7aa1c00,
  "https://www.prapatti.com/slokas/tamil/tiruttanjaimaamanikkoyilpaasurangal.pdf": pdf_0cd460eeed23a2e692eda05ed660c89c,
  "https://www.prapatti.com/slokas/sanskrit/tiruttanjaimaamanikkoyilpaasurangal.pdf": pdf_76612f6186454882244f4431a0ca8cd2,
  "https://www.prapatti.com/slokas/kannada/tiruttanjaimaamanikkoyilpaasurangal.pdf": pdf_8ea1f297605e3cab1b447d95db92632d,
  "https://www.prapatti.com/slokas/english/tiruttanjaimaamanikkoyilpaasurangal.pdf": pdf_9a5498ec369fda1aa9d1a9e7c500e31a,
  "https://www.prapatti.com/slokas/tamil/tiruyevvulpaasurangal.pdf": pdf_2dbbc2b8cf08d1c5cd25d973dfb1e939,
  "https://www.prapatti.com/slokas/sanskrit/tiruyevvulpaasurangal.pdf": pdf_8691a5ba68fee519908e654207edcbb7,
  "https://www.prapatti.com/slokas/kannada/tiruyevvulpaasurangal.pdf": pdf_347db061d536ef2326b78fd3811eb4f4,
  "https://www.prapatti.com/slokas/english/tiruyevvulpaasurangal.pdf": pdf_d0c208c705ffdcf7eb1ab8dc6e41983f,
  "https://www.prapatti.com/slokas/sanskrit/tirunaimicaaranyampaasurangal.pdf": pdf_04a01857e104384ba60be707db447a9e,
  "https://www.prapatti.com/slokas/kannada/tirunaimicaaranyampaasurangal.pdf": pdf_83d7dd6fa62e784b557703e297a99fc7,
  "https://www.prapatti.com/slokas/english/tirunaimicaaranyampaasurangal.pdf": pdf_b3f0b287018cc6d7361d8311fae41d52,
  "https://www.prapatti.com/slokas/tamil/tirunaimicaaranyampaasurangal.pdf": pdf_bfab3d1a5aaec9af390804489e1f5148,
  "https://www.prapatti.com/slokas/sanskrit/tiruvaadanuurpaasurangal.pdf": pdf_90c4abf8019e9e009e2ac2e02c21da50,
  "https://www.prapatti.com/slokas/english/tiruvaadanuurpaasurangal.pdf": pdf_d92c60a904bfc598311cbc8abce61d08,
  "https://www.prapatti.com/slokas/kannada/tiruvaadanuurpaasurangal.pdf": pdf_be0a6d62b14271ae9629cbec57c5f529,
  "https://www.prapatti.com/slokas/tamil/tiruvaadanuurpaasurangal.pdf": pdf_66d4be8a2a09c0f28c599a221111bb7c,
  "https://www.prapatti.com/slokas/english/tiruyarimeyavinnagarampaasurangal.pdf": pdf_4820c888f3949c8358fd2e3de62589c6,
  "https://www.prapatti.com/slokas/tamil/tiruyarimeyavinnagarampaasurangal.pdf": pdf_e12de99ae58e2c7c15fa515d7adfc76e,
  "https://www.prapatti.com/slokas/kannada/tiruyarimeyavinnagarampaasurangal.pdf": pdf_31a1c116a887b675276992c7271ac87f,
  "https://www.prapatti.com/slokas/sanskrit/tiruyarimeyavinnagarampaasurangal.pdf": pdf_4cd1d34d1388f43d24bb5490a74af5b9,
  "https://www.prapatti.com/slokas/sanskrit/tiruvattabhuyakarampaasurangal.pdf": pdf_f95a170c6593d2cde21b10fa3d6ea7e5,
  "https://www.prapatti.com/slokas/english/tiruvattabhuyakarampaasurangal.pdf": pdf_c1d81873117034d4235ed47778f92516,
  "https://www.prapatti.com/slokas/kannada/tiruvattabhuyakarampaasurangal.pdf": pdf_f8ccdd5934652dd038ac8539430b4155,
  "https://www.prapatti.com/slokas/tamil/tiruvattabhuyakarampaasurangal.pdf": pdf_09202bd7258431fe74c835118628d046,
  "https://www.prapatti.com/slokas/english/tiruvayoddhipaasurangal.pdf": pdf_d97cba806c0f36a7272ca477faf63f6e,
  "https://www.prapatti.com/slokas/sanskrit/tiruvayoddhipaasurangal.pdf": pdf_040eacd95f06127ea17c836e8b3a63ef,
  "https://www.prapatti.com/slokas/kannada/tiruvayoddhipaasurangal.pdf": pdf_3e59e91e3b437b47983b72de670a26ae,
  "https://www.prapatti.com/slokas/tamil/tiruvayoddhipaasurangal.pdf": pdf_58654474fcc28a6429ef22b6b6d5540b,
  "https://www.prapatti.com/slokas/english/tiruccaalagraamampaasurangal.pdf": pdf_d36eac863af9c2436b39356130174af7,
  "https://www.prapatti.com/slokas/sanskrit/tiruccaalagraamampaasurangal.pdf": pdf_859ef6bcb02bf405966143223b1e6c83,
  "https://www.prapatti.com/slokas/tamil/tiruccaalagraamampaasurangal.pdf": pdf_887565567ad5ba9f85a4c70e0de6a6e8,
  "https://www.prapatti.com/slokas/kannada/tiruccaalagraamampaasurangal.pdf": pdf_fd0667dffbbf7b60b6ffd2cac623ccb8,
  "https://www.prapatti.com/slokas/sanskrit/tiruccengunruurpaasurangal.pdf": pdf_542e5d7e7d2996bf41be177f3dd1b39d,
  "https://www.prapatti.com/slokas/tamil/tiruccengunruurpaasurangal.pdf": pdf_603ce4336a9ec2bfa63284b9241b15ea,
  "https://www.prapatti.com/slokas/english/tiruccengunruurpaasurangal.pdf": pdf_df35c86eee3c2fdf3bdac8def9ebdafc,
  "https://www.prapatti.com/slokas/kannada/tiruccengunruurpaasurangal.pdf": pdf_44340f241b98300e9f4aab50c3d2891f,
  "https://www.prapatti.com/slokas/kannada/tirucceraipaasurangal.pdf": pdf_b61dfee72d010525d308b772a4dd1e72,
  "https://www.prapatti.com/slokas/english/tirucceraipaasurangal.pdf": pdf_e19ba9ce3431213a7079aa1fabe1f79e,
  "https://www.prapatti.com/slokas/tamil/tirucceraipaasurangal.pdf": pdf_dece0bd58e148dee049717f8e16f15f9,
  "https://www.prapatti.com/slokas/sanskrit/tirucceraipaasurangal.pdf": pdf_d2f32d6a58911c12d52ad2f0ac2f9c2b,
  "https://www.prapatti.com/slokas/english/tirucciriivaramangaipaasurangal.pdf": pdf_623c954516bb1c122ec2ed6ef99c4f59,
  "https://www.prapatti.com/slokas/tamil/tirucciriivaramangaipaasurangal.pdf": pdf_fcd13994d4b972fec29e4cfa904537ff,
  "https://www.prapatti.com/slokas/sanskrit/tirucciriivaramangaipaasurangal.pdf": pdf_19a5cd6af013b5b522e15c9ce0019649,
  "https://www.prapatti.com/slokas/kannada/tirucciriivaramangaipaasurangal.pdf": pdf_074489fdf89e2b8766b7e1bafed58436,
  "https://www.prapatti.com/slokas/tamil/tiruccirupuliyuurpaasurangal.pdf": pdf_cb104352eeae7f85d146ffcc72ea3c9d,
  "https://www.prapatti.com/slokas/english/tiruccirupuliyuurpaasurangal.pdf": pdf_d078e39ef11395084dbbc88d93f07806,
  "https://www.prapatti.com/slokas/sanskrit/tiruccirupuliyuurpaasurangal.pdf": pdf_f0bd0421801019105c359e918ebf2c65,
  "https://www.prapatti.com/slokas/kannada/tiruccirupuliyuurpaasurangal.pdf": pdf_ab283be1ae3e626c49d13db46839cd31,
  "https://www.prapatti.com/slokas/english/tiruccitrakuudampaasurangal.pdf": pdf_c6f30bd3363e956abd2420dc12fe0165,
  "https://www.prapatti.com/slokas/sanskrit/tiruccitrakuudampaasurangal.pdf": pdf_dc3af2cac0b19f1f2838ec727b8b8f09,
  "https://www.prapatti.com/slokas/kannada/tiruccitrakuudampaasurangal.pdf": pdf_96b78212638e6a7c8c8de5c86a1bd951,
  "https://www.prapatti.com/slokas/tamil/tiruccitrakuudampaasurangal.pdf": pdf_6961d2f17b6637c4940264fd774c0529,
  "https://www.prapatti.com/slokas/sanskrit/tiruttevanaartogaipaasurangal.pdf": pdf_8b72e9c7dc7bc5bebc38908f2351a72a,
  "https://www.prapatti.com/slokas/tamil/tiruttevanaartogaipaasurangal.pdf": pdf_e7c476ab8031c07c906d267b7ec6e5d4,
  "https://www.prapatti.com/slokas/english/tiruttevanaartogaipaasurangal.pdf": pdf_fb2d90bc0c750f2ceec1c801b7a15ce3,
  "https://www.prapatti.com/slokas/kannada/tiruttevanaartogaipaasurangal.pdf": pdf_ebe9efddc7c4976b16fc0c8e6bcb1567,
  "https://www.prapatti.com/slokas/tamil/tirudvaarakaipaasurangal.pdf": pdf_6d40338d62faa20b1737f5513f692c8c,
  "https://www.prapatti.com/slokas/sanskrit/tirudvaarakaipaasurangal.pdf": pdf_a46ccd8bad1fafb30ef4b701b1596ea9,
  "https://www.prapatti.com/slokas/english/tirudvaarakaipaasurangal.pdf": pdf_d597d71c0c874cfb612426b7135b9fd5,
  "https://www.prapatti.com/slokas/kannada/tirudvaarakaipaasurangal.pdf": pdf_1bdb515e3be0700c909d2d9471fad67b,
  "https://www.prapatti.com/slokas/kannada/tiruvindaluurpaasurangal.pdf": pdf_3d683867ba7d4efbe60ded8a5258ee69,
  "https://www.prapatti.com/slokas/sanskrit/tiruvindaluurpaasurangal.pdf": pdf_3bf0482f2666190093e66342f7f51be9,
  "https://www.prapatti.com/slokas/tamil/tiruvindaluurpaasurangal.pdf": pdf_384c30b4aa34ebc21434a5ef613159fa,
  "https://www.prapatti.com/slokas/english/tiruvindaluurpaasurangal.pdf": pdf_2d6b3c3ab8f83a3614d52c7f23b2f749,
  "https://www.prapatti.com/slokas/english/tirukkaaragampaasurangal.pdf": pdf_6074922f04bf906977e036c9233b4b4d,
  "https://www.prapatti.com/slokas/sanskrit/tirukkaaragampaasurangal.pdf": pdf_2ff756439fdf803a326fecdfa48a5a3a,
  "https://www.prapatti.com/slokas/kannada/tirukkaaragampaasurangal.pdf": pdf_2bd4f6f9901ebfdafca15b30dd52ee13,
  "https://www.prapatti.com/slokas/tamil/tirukkaaragampaasurangal.pdf": pdf_38987b84104a301e9ecfed87fcf00882,
  "https://www.prapatti.com/slokas/tamil/tirukkaarvaanampaasurangal.pdf": pdf_49910d1f8529b8da5031bc6f7dc6b167,
  "https://www.prapatti.com/slokas/kannada/tirukkaarvaanampaasurangal.pdf": pdf_ee2eda4216510707eac4304a34cc41ff,
  "https://www.prapatti.com/slokas/english/tirukkaarvaanampaasurangal.pdf": pdf_20a798bee7e50ccb41054c76a56d7805,
  "https://www.prapatti.com/slokas/sanskrit/tirukkaarvaanampaasurangal.pdf": pdf_107c56eacfed016349cb3996d9309177,
  "https://www.prapatti.com/slokas/tamil/tirukkaccipaasurangal.pdf": pdf_ea33c958f5b8b6d78bb3340247ae0052,
  "https://www.prapatti.com/slokas/sanskrit/tirukkaccipaasurangal.pdf": pdf_9642f5b946bae81ffa02e465650ea490,
  "https://www.prapatti.com/slokas/english/tirukkaccipaasurangal.pdf": pdf_0950d5eb1b232b85697ea775ecd7c819,
  "https://www.prapatti.com/slokas/kannada/tirukkaccipaasurangal.pdf": pdf_ba616d544498fa9d08665e62a9ad7036,
  "https://www.prapatti.com/slokas/tamil/tirukkadalmallaipaasurangal.pdf": pdf_84749dd75d697ad6efcad6ec2c1a6a49,
  "https://www.prapatti.com/slokas/sanskrit/tirukkadalmallaipaasurangal.pdf": pdf_082b09ca86cac5c9274bba5f1b63d01d,
  "https://www.prapatti.com/slokas/kannada/tirukkadalmallaipaasurangal.pdf": pdf_24d018d790879553b79f5dd972bb9c6d,
  "https://www.prapatti.com/slokas/english/tirukkadalmallaipaasurangal.pdf": pdf_d8de5ffda59b88b84258c972b2e5e94d,
  "https://www.prapatti.com/slokas/kannada/tirukkaatkaraipaasurangal.pdf": pdf_001e17f7c50ba1d9c15e9447b00a46de,
  "https://www.prapatti.com/slokas/tamil/tirukkaatkaraipaasurangal.pdf": pdf_00aecf37b8c162b54183470af23fa9ba,
  "https://www.prapatti.com/slokas/sanskrit/tirukkaatkaraipaasurangal.pdf": pdf_1f2be7d5b2a6feb24dba25a931303ffc,
  "https://www.prapatti.com/slokas/english/tirukkaatkaraipaasurangal.pdf": pdf_39585b562b6f81d73b2dd7c9fc428bf4,
  "https://www.prapatti.com/slokas/sanskrit/tirukkalvanuurpaasurangal.pdf": pdf_ce6531d6f7325a976bdd83886e764183,
  "https://www.prapatti.com/slokas/kannada/tirukkalvanuurpaasurangal.pdf": pdf_98fc339d96ae1619d8795bcec83893f4,
  "https://www.prapatti.com/slokas/english/tirukkalvanuurpaasurangal.pdf": pdf_4502a4cdfc9c90725e110aa16b38012a,
  "https://www.prapatti.com/slokas/tamil/tirukkalvanuurpaasurangal.pdf": pdf_5d257b979b5658134f6015dafae4f6b1,
  "https://www.prapatti.com/slokas/tamil/tirukkannamangaipaasurangal.pdf": pdf_69b39b1d78f147545a088f408da7271c,
  "https://www.prapatti.com/slokas/kannada/tirukkannamangaipaasurangal.pdf": pdf_77d56564227c6e19c3e270f9d6ea4eb2,
  "https://www.prapatti.com/slokas/sanskrit/tirukkannamangaipaasurangal.pdf": pdf_1a1102082d91cbeee55d1e3d8b3eab11,
  "https://www.prapatti.com/slokas/english/tirukkannamangaipaasurangal.pdf": pdf_14695f8d74ba6bb79720504572d77188,
  "https://www.prapatti.com/slokas/sanskrit/tirukkannangudipaasurangal.pdf": pdf_53a9c93dc065df39631bbdcce9a2a3b1,
  "https://www.prapatti.com/slokas/english/tirukkannangudipaasurangal.pdf": pdf_8b188b4a44f7524b98b13486cb371ff7,
  "https://www.prapatti.com/slokas/kannada/tirukkannangudipaasurangal.pdf": pdf_c7a1455e41c01e09b08fbf5063eab51a,
  "https://www.prapatti.com/slokas/tamil/tirukkannangudipaasurangal.pdf": pdf_abc546d2fa89356b7e4e5a09417fa600,
  "https://www.prapatti.com/slokas/tamil/tirukkannapurampaasurangal.pdf": pdf_77d503a7b71a4e8612180b7c10dec75c,
  "https://www.prapatti.com/slokas/english/tirukkannapurampaasurangal.pdf": pdf_3eb754d53398d057919e451979189d8b,
  "https://www.prapatti.com/slokas/sanskrit/tirukkannapurampaasurangal.pdf": pdf_cc77b3f234526c6486e5a99cacbb1f26,
  "https://www.prapatti.com/slokas/kannada/tirukkannapurampaasurangal.pdf": pdf_89b07799702a64e1b8747f618d4ffba5,
  "https://www.prapatti.com/slokas/tamil/tirukkarambanuurpaasurangal.pdf": pdf_98c8ba56001cb19203fa5bb25b958291,
  "https://www.prapatti.com/slokas/sanskrit/tirukkarambanuurpaasurangal.pdf": pdf_bf882f4dbda1fc98d8a7326804cd0c89,
  "https://www.prapatti.com/slokas/kannada/tirukkarambanuurpaasurangal.pdf": pdf_a62f7c78c39dfc91d32962518c11e98b,
  "https://www.prapatti.com/slokas/english/tirukkarambanuurpaasurangal.pdf": pdf_4d988c41b9e4108f07baec532c53fce8,
  "https://www.prapatti.com/slokas/english/tirukkaazicciiraamavinnagarampaasurangal.pdf": pdf_8b7c2687f813f20888cda8abbff8031f,
  "https://www.prapatti.com/slokas/sanskrit/tirukkaazicciiraamavinnagarampaasurangal.pdf": pdf_de63368c2964274ca2fce085016f5752,
  "https://www.prapatti.com/slokas/tamil/tirukkaazicciiraamavinnagarampaasurangal.pdf": pdf_2b4a2c7f1b2dd53976ae0f73a3371744,
  "https://www.prapatti.com/slokas/kannada/tirukkaazicciiraamavinnagarampaasurangal.pdf": pdf_a5846b1bf78424f781394d4bde5b6fe4,
  "https://www.prapatti.com/slokas/tamil/tirukkadigaipaasurangal.pdf": pdf_09e563a35829c5f413b2bc47acd8ecd4,
  "https://www.prapatti.com/slokas/english/tirukkadigaipaasurangal.pdf": pdf_74c07df2dedb537171ea7142aed10810,
  "https://www.prapatti.com/slokas/kannada/tirukkadigaipaasurangal.pdf": pdf_0c885ee053b6a80336c1b9b9098a078b,
  "https://www.prapatti.com/slokas/sanskrit/tirukkadigaipaasurangal.pdf": pdf_4e03e6f8624a87b685d62557ca47fb5a,
  "https://www.prapatti.com/slokas/english/tirukkandampaasurangal.pdf": pdf_d971a13cf1c2287596e6264bac051bb4,
  "https://www.prapatti.com/slokas/kannada/tirukkandampaasurangal.pdf": pdf_e76da10c76c75d99a67fa979fb3966a5,
  "https://www.prapatti.com/slokas/tamil/tirukkandampaasurangal.pdf": pdf_1b1042ebf6493f28360725c091bf5d5b,
  "https://www.prapatti.com/slokas/sanskrit/tirukkandampaasurangal.pdf": pdf_85e73e8a01169b0152a476fd1e34c873,
  "https://www.prapatti.com/slokas/kannada/tirukkandiyuurpaasurangal.pdf": pdf_a2309545e516a72dbb010c88d7f30832,
  "https://www.prapatti.com/slokas/sanskrit/tirukkandiyuurpaasurangal.pdf": pdf_3564617925a41ebc22b983fce69ca43a,
  "https://www.prapatti.com/slokas/tamil/tirukkandiyuurpaasurangal.pdf": pdf_26c683d546a4ca5f6466e71f556dfaa9,
  "https://www.prapatti.com/slokas/english/tirukkandiyuurpaasurangal.pdf": pdf_94ccabb6d89373840c0084edd51cef14,
  "https://www.prapatti.com/slokas/tamil/tirukkoluurpaasurangal.pdf": pdf_2ed3501d28fbfefb0da7c341a240fdee,
  "https://www.prapatti.com/slokas/kannada/tirukkoluurpaasurangal.pdf": pdf_8bb3ccd6383ef78c16738f5923fa88f2,
  "https://www.prapatti.com/slokas/english/tirukkoluurpaasurangal.pdf": pdf_45783e32ef6ae0ff676855685808e910,
  "https://www.prapatti.com/slokas/sanskrit/tirukkoluurpaasurangal.pdf": pdf_30c693c78ce1c1275319e1db7c962c56,
  "https://www.prapatti.com/slokas/tamil/tirukkuudaluurpaasurangal.pdf": pdf_7fb695672d8c222a6460500e9a0a885b,
  "https://www.prapatti.com/slokas/english/tirukkuudaluurpaasurangal.pdf": pdf_c49584e64827a9f2534cb12f5abc1228,
  "https://www.prapatti.com/slokas/kannada/tirukkuudaluurpaasurangal.pdf": pdf_38d93c44bb560755f7ec276d3bf6c612,
  "https://www.prapatti.com/slokas/sanskrit/tirukkuudaluurpaasurangal.pdf": pdf_a9641f675daf9305059c1799c2d6d3cd,
  "https://www.prapatti.com/slokas/english/tirukkottiyuurpaasurangal.pdf": pdf_098ebe89bd6606aa168d5a7048860898,
  "https://www.prapatti.com/slokas/tamil/tirukkottiyuurpaasurangal.pdf": pdf_ae744dfb8bec79908d85d3a0e5ca62fb,
  "https://www.prapatti.com/slokas/sanskrit/tirukkottiyuurpaasurangal.pdf": pdf_0e6d679a1e1d55fc59f0812a06278df5,
  "https://www.prapatti.com/slokas/kannada/tirukkottiyuurpaasurangal.pdf": pdf_ad6fafaefc1e1d09461c8b2ca431460d,
  "https://www.prapatti.com/slokas/tamil/tirukkovaluurpaasurangal.pdf": pdf_83c5ecf85f335bacbf3c757c705bc675,
  "https://www.prapatti.com/slokas/kannada/tirukkovaluurpaasurangal.pdf": pdf_a7fe82c11c78825dad655380bd8a4c5c,
  "https://www.prapatti.com/slokas/english/tirukkovaluurpaasurangal.pdf": pdf_3093a5770b568a8c3a10e8b5b1925aa8,
  "https://www.prapatti.com/slokas/sanskrit/tirukkovaluurpaasurangal.pdf": pdf_749242df1cd0e9d508d508b000df648c,
  "https://www.prapatti.com/slokas/sanskrit/tirukkozipaasurangal.pdf": pdf_ce3bb0b65e7c860deac387fccb90850f,
  "https://www.prapatti.com/slokas/tamil/tirukkozipaasurangal.pdf": pdf_7342d2af1077f4af7a6abd21b291035c,
  "https://www.prapatti.com/slokas/kannada/tirukkozipaasurangal.pdf": pdf_41ff6f93cd043bfc0ef0159d16b39172,
  "https://www.prapatti.com/slokas/english/tirukkozipaasurangal.pdf": pdf_2abc8a7f6d321fa7da6ce9cb75857256,
  "https://www.prapatti.com/slokas/sanskrit/tirukkudandaipaasurangal.pdf": pdf_4e49e389d706a5c26d149aa7612882c4,
  "https://www.prapatti.com/slokas/tamil/tirukkudandaipaasurangal.pdf": pdf_1f9f8d30b305cd9d230c15b0719fd1f1,
  "https://www.prapatti.com/slokas/kannada/tirukkudandaipaasurangal.pdf": pdf_13255b159caf5f544e8e142caa68ad06,
  "https://www.prapatti.com/slokas/english/tirukkudandaipaasurangal.pdf": pdf_42f79bab7a414379d96834d78d797fff,
  "https://www.prapatti.com/slokas/sanskrit/tirukkulandaipaasurangal.pdf": pdf_60a26488beab6c598f633916abe0813b,
  "https://www.prapatti.com/slokas/english/tirukkulandaipaasurangal.pdf": pdf_ed42eda4fc0538c98d52e5565207c9b4,
  "https://www.prapatti.com/slokas/kannada/tirukkulandaipaasurangal.pdf": pdf_75667f3535c8e2b5211bd674fffbd9cc,
  "https://www.prapatti.com/slokas/tamil/tirukkulandaipaasurangal.pdf": pdf_013dd9d87ebfdf3db2cd98d32db5fd32,
  "https://www.prapatti.com/slokas/english/tirukkuruguurpaasurangal.pdf": pdf_e73af7e7b4d0cf221d3cc5b1a929f146,
  "https://www.prapatti.com/slokas/kannada/tirukkuruguurpaasurangal.pdf": pdf_41861656e8d129ebd8fe3b424bf755e3,
  "https://www.prapatti.com/slokas/sanskrit/tirukkuruguurpaasurangal.pdf": pdf_7645310d908c6c5b000cf9cd4cadb87c,
  "https://www.prapatti.com/slokas/tamil/tirukkuruguurpaasurangal.pdf": pdf_45f498e670be36354e0bb057c5e0981a,
  "https://www.prapatti.com/slokas/sanskrit/tirukkadittaanampaasurangal.pdf": pdf_2a924982e803d689b9b5c97bc9313962,
  "https://www.prapatti.com/slokas/kannada/tirukkadittaanampaasurangal.pdf": pdf_4035421d77b134a15f3b27b57b2945d4,
  "https://www.prapatti.com/slokas/tamil/tirukkadittaanampaasurangal.pdf": pdf_12287bccb75d133e9486c9878ff44c2d,
  "https://www.prapatti.com/slokas/english/tirukkadittaanampaasurangal.pdf": pdf_a554296e6d520e369fd411fa399c641e,
  "https://www.prapatti.com/slokas/english/tirukkuudalpaasurangal.pdf": pdf_a87080ed690db8d40a7198f8a80b571c,
  "https://www.prapatti.com/slokas/sanskrit/tirukkuudalpaasurangal.pdf": pdf_71a34d41c83c85920ae2753d948230ff,
  "https://www.prapatti.com/slokas/tamil/tirukkuudalpaasurangal.pdf": pdf_b8dac491c4ddbac02a79ba2a6037e025,
  "https://www.prapatti.com/slokas/kannada/tirukkuudalpaasurangal.pdf": pdf_6f110113a6b1db916855804167aa8665,
  "https://www.prapatti.com/slokas/sanskrit/tirukkurungudipaasurangal.pdf": pdf_ab6a91aaf69ecde2d19eaba806a60a4b,
  "https://www.prapatti.com/slokas/english/tirukkurungudipaasurangal.pdf": pdf_6e1d76207b7531acb4aa5f348c347497,
  "https://www.prapatti.com/slokas/kannada/tirukkurungudipaasurangal.pdf": pdf_83fe0594ecfeecf3dcc3cd497027d429,
  "https://www.prapatti.com/slokas/tamil/tirukkurungudipaasurangal.pdf": pdf_ffb48e24472cddacd636cb8d522cfa2b,
  "https://www.prapatti.com/slokas/sanskrit/tirumaalirunjolaipaasurangal.pdf": pdf_d5968115f4ff0470d30df2f2cc386972,
  "https://www.prapatti.com/slokas/english/tirumaalirunjolaipaasurangal.pdf": pdf_ddaeced0756d392db1f4b4881bf4331e,
  "https://www.prapatti.com/slokas/tamil/tirumaalirunjolaipaasurangal.pdf": pdf_418e60abd5df4a53730c33353850ecc1,
  "https://www.prapatti.com/slokas/kannada/tirumaalirunjolaipaasurangal.pdf": pdf_a5f1def787c9f8aa110dcfcf4744a10b,
  "https://www.prapatti.com/slokas/english/tirumanimaadakkoyilpaasurangal.pdf": pdf_a59f91898b79c2358ac7d09c9fdd7316,
  "https://www.prapatti.com/slokas/kannada/tirumanimaadakkoyilpaasurangal.pdf": pdf_29cab62cfd249286cca2d95465d5ee0c,
  "https://www.prapatti.com/slokas/tamil/tirumanimaadakkoyilpaasurangal.pdf": pdf_371ba8522e050d5fc8c2128b39f086a0,
  "https://www.prapatti.com/slokas/sanskrit/tirumanimaadakkoyilpaasurangal.pdf": pdf_be6b712869b41d4421bbe3a5b4bdc3eb,
  "https://www.prapatti.com/slokas/sanskrit/tirumeyyampaasurangal.pdf": pdf_7588328853d7956717620c1b3177cfee,
  "https://www.prapatti.com/slokas/english/tirumeyyampaasurangal.pdf": pdf_656d542f000e5c04556208d1db430457,
  "https://www.prapatti.com/slokas/tamil/tirumeyyampaasurangal.pdf": pdf_665e60087915483bd471c81874b1619a,
  "https://www.prapatti.com/slokas/kannada/tirumeyyampaasurangal.pdf": pdf_e1a11211ac0305dab30a27d85b8c9b61,
  "https://www.prapatti.com/slokas/sanskrit/tirumoguurpaasurangal.pdf": pdf_ab27f9a0f094a57658089b29e6a041ee,
  "https://www.prapatti.com/slokas/tamil/tirumoguurpaasurangal.pdf": pdf_f22f9ad75b01ec9a13b567099aec191d,
  "https://www.prapatti.com/slokas/english/tirumoguurpaasurangal.pdf": pdf_68efe14e656c2cc55624e3551d1ffdf9,
  "https://www.prapatti.com/slokas/kannada/tirumoguurpaasurangal.pdf": pdf_de7a1586932d7ff1aa67fbb67b98d9a8,
  "https://www.prapatti.com/slokas/sanskrit/tirumuuzikkalampaasurangal.pdf": pdf_4ba21f8eb693ed89d6cf47fc9969a86c,
  "https://www.prapatti.com/slokas/english/tirumuuzikkalampaasurangal.pdf": pdf_e5c2aca1bb72e5c709d3de776a92660a,
  "https://www.prapatti.com/slokas/kannada/tirumuuzikkalampaasurangal.pdf": pdf_84dc278992f326039491d25eedcf9f41,
  "https://www.prapatti.com/slokas/tamil/tirumuuzikkalampaasurangal.pdf": pdf_f6797c85a1e11b00fe73cad6f801292b,
  "https://www.prapatti.com/slokas/english/tirunaagaipaasurangal.pdf": pdf_e7edfa7feeadad11658e7274e0090999,
  "https://www.prapatti.com/slokas/kannada/tirunaagaipaasurangal.pdf": pdf_1b61b8c1baaa414f20d2ffebb2d66454,
  "https://www.prapatti.com/slokas/sanskrit/tirunaagaipaasurangal.pdf": pdf_77ccfee78ee04b558696afec3a017e17,
  "https://www.prapatti.com/slokas/tamil/tirunaagaipaasurangal.pdf": pdf_4eb0df285963fe7fcfce6dc350751b11,
  "https://www.prapatti.com/slokas/tamil/tirunaavaaypaasurangal.pdf": pdf_8f43dcfe3951ad5ef52e14d477c50ff9,
  "https://www.prapatti.com/slokas/kannada/tirunaavaaypaasurangal.pdf": pdf_07ad26f570223877a5601f51c48a33a0,
  "https://www.prapatti.com/slokas/sanskrit/tirunaavaaypaasurangal.pdf": pdf_f0ca3253790fb56440290d9d27980a52,
  "https://www.prapatti.com/slokas/english/tirunaavaaypaasurangal.pdf": pdf_bc1072303859f6884a4cefc3ce132530,
  "https://www.prapatti.com/slokas/tamil/tirunandipuravinnagarampaasurangal.pdf": pdf_8900a941d37e5a5488b9c8a51293892c,
  "https://www.prapatti.com/slokas/english/tirunandipuravinnagarampaasurangal.pdf": pdf_eab488407cef44157a6fbfeb71abf7da,
  "https://www.prapatti.com/slokas/sanskrit/tirunandipuravinnagarampaasurangal.pdf": pdf_f4e1c51281aa850e083bdb47117f41ff,
  "https://www.prapatti.com/slokas/kannada/tirunandipuravinnagarampaasurangal.pdf": pdf_c6fac6267eb38c0ac27e8696902943d9,
  "https://www.prapatti.com/slokas/english/tirukkaavalampaadipaasurangal.pdf": pdf_59442ea8c718ddcce6e0b620358fe766,
  "https://www.prapatti.com/slokas/tamil/tirukkaavalampaadipaasurangal.pdf": pdf_ceedf02e1b1594d1b9dfe835f423001a,
  "https://www.prapatti.com/slokas/sanskrit/tirukkaavalampaadipaasurangal.pdf": pdf_21047c84fc00295b8bdea3b4d22f5b7c,
  "https://www.prapatti.com/slokas/kannada/tirukkaavalampaadipaasurangal.pdf": pdf_3bae2b70bfb3d855082258991f742596,
  "https://www.prapatti.com/slokas/kannada/tiruniiragampaasurangal.pdf": pdf_141cd67ac2ed7d0a2583dd8145445bfb,
  "https://www.prapatti.com/slokas/english/tiruniiragampaasurangal.pdf": pdf_3f054532f80552a0ee1665a55d658a27,
  "https://www.prapatti.com/slokas/sanskrit/tiruniiragampaasurangal.pdf": pdf_76c382549d741dc47d9be70a22bea01a,
  "https://www.prapatti.com/slokas/tamil/tiruniiragampaasurangal.pdf": pdf_d9732d86c7ff689d451f92c6b6eda0fd,
  "https://www.prapatti.com/slokas/kannada/tiruniirmalaipaasurangal.pdf": pdf_21a568f413c05da84fef4896a9be126e,
  "https://www.prapatti.com/slokas/english/tiruniirmalaipaasurangal.pdf": pdf_1ff275d0e0499595fbf01acf0d008a44,
  "https://www.prapatti.com/slokas/sanskrit/tiruniirmalaipaasurangal.pdf": pdf_034acea95332193cfa44dbf9f34daa66,
  "https://www.prapatti.com/slokas/tamil/tiruniirmalaipaasurangal.pdf": pdf_bbee840345175eed9b15a0b7e148e243,
  "https://www.prapatti.com/slokas/english/tirunilaattingaltundampaasurangal.pdf": pdf_36864ac55aca0a1b124f59268edbc8b2,
  "https://www.prapatti.com/slokas/tamil/tirunilaattingaltundampaasurangal.pdf": pdf_7c519ed12ff5b1df53e93c421e79b6aa,
  "https://www.prapatti.com/slokas/sanskrit/tirunilaattingaltundampaasurangal.pdf": pdf_8370de95c174cc7e95533d393d7e2e2b,
  "https://www.prapatti.com/slokas/kannada/tirunilaattingaltundampaasurangal.pdf": pdf_f00e5d0ecedfb380a1dfde244d0a89ff,
  "https://www.prapatti.com/slokas/english/tiruninravuurpaasurangal.pdf": pdf_0c7ded7a180b848a63d7effe04bc947d,
  "https://www.prapatti.com/slokas/tamil/tiruninravuurpaasurangal.pdf": pdf_b7b25dde6a80289bfe3068984800d3a5,
  "https://www.prapatti.com/slokas/kannada/tiruninravuurpaasurangal.pdf": pdf_6fbed6c210e2c6f84cae188cf0650c85,
  "https://www.prapatti.com/slokas/sanskrit/tiruninravuurpaasurangal.pdf": pdf_17c0df6f37604372b03435df65219a0a,
  "https://www.prapatti.com/slokas/sanskrit/tiruyuuragampaasurangal.pdf": pdf_cb00e69a9ee69c5027657c4b90ca4ea9,
  "https://www.prapatti.com/slokas/kannada/tiruyuuragampaasurangal.pdf": pdf_197e87f905003d5a67174b57f426b70b,
  "https://www.prapatti.com/slokas/tamil/tiruyuuragampaasurangal.pdf": pdf_f81ab458325f02f6c3f09968f0d2efef,
  "https://www.prapatti.com/slokas/english/tiruyuuragampaasurangal.pdf": pdf_8c93dd300629028444b26b16c2144692,
  "https://www.prapatti.com/slokas/tamil/tiruppaadagampaasurangal.pdf": pdf_c73a72dfe0a1acf1d6e11dd19ce0e146,
  "https://www.prapatti.com/slokas/sanskrit/tiruppaadagampaasurangal.pdf": pdf_a9b9d9882c21bb6cf231c2ed30145929,
  "https://www.prapatti.com/slokas/english/tiruppaadagampaasurangal.pdf": pdf_dd3031e68763e67372fc87deb7b1d107,
  "https://www.prapatti.com/slokas/kannada/tiruppaadagampaasurangal.pdf": pdf_38d6f3c950432cce1cef27bf066cc555,
  "https://www.prapatti.com/slokas/kannada/tirupparamapadampaasurangal.pdf": pdf_0f24441b5bda00d0e57c44249925a49f,
  "https://www.prapatti.com/slokas/sanskrit/tirupparamapadampaasurangal.pdf": pdf_7de977ead6ed0f27ad79bf3f1f3ff34f,
  "https://www.prapatti.com/slokas/english/tirupparamapadampaasurangal.pdf": pdf_c8b60f44e9c3ae4b10452220902a912d,
  "https://www.prapatti.com/slokas/tamil/tirupparamapadampaasurangal.pdf": pdf_84c3fc1a212ac41dc3de050fc335f67f,
  "https://www.prapatti.com/slokas/kannada/tirupparameccuravinnagarampaasurangal.pdf": pdf_0860a5ee5d123e41be6ee6730f78d4fe,
  "https://www.prapatti.com/slokas/tamil/tirupparameccuravinnagarampaasurangal.pdf": pdf_c2c760e76a5a24d62a6d70c6148726cf,
  "https://www.prapatti.com/slokas/sanskrit/tirupparameccuravinnagarampaasurangal.pdf": pdf_f97efac654e92436771fc805fdf36fa9,
  "https://www.prapatti.com/slokas/english/tirupparameccuravinnagarampaasurangal.pdf": pdf_49db4a044d00b4c819d9c233117daade,
  "https://www.prapatti.com/slokas/kannada/tiruppaarkadalpaasurangal.pdf": pdf_df099b0d1386901d4e2af91dd85d597b,
  "https://www.prapatti.com/slokas/english/tiruppaarkadalpaasurangal.pdf": pdf_2a2b2cecc20a80e3572dbcc77a07b415,
  "https://www.prapatti.com/slokas/sanskrit/tiruppaarkadalpaasurangal.pdf": pdf_117d10430465877211dce73ca16cb268,
  "https://www.prapatti.com/slokas/tamil/tiruppaarkadalpaasurangal.pdf": pdf_c032b3c714b063f27d4e0392beab26d4,
  "https://www.prapatti.com/slokas/tamil/tirupperpaasurangal.pdf": pdf_299e9f20bdda4f2d6704550037b2a07b,
  "https://www.prapatti.com/slokas/sanskrit/tirupperpaasurangal.pdf": pdf_0b36554728d9ad045b446704d6deb372,
  "https://www.prapatti.com/slokas/english/tirupperpaasurangal.pdf": pdf_2c9f8afbbcb0beb22e1d84313c36df95,
  "https://www.prapatti.com/slokas/kannada/tirupperpaasurangal.pdf": pdf_952a2a6956887f840fc58ce0fa04f28c,
  "https://www.prapatti.com/slokas/kannada/tirupaartthanpallipaasurangal.pdf": pdf_2640138c4e49591ed99ad2292057f4f5,
  "https://www.prapatti.com/slokas/tamil/tirupaartthanpallipaasurangal.pdf": pdf_eafdf6a3ca66e33e75a114ffdefe0855,
  "https://www.prapatti.com/slokas/english/tirupaartthanpallipaasurangal.pdf": pdf_d74b834e873f7d76d55fd1b991d70d1b,
  "https://www.prapatti.com/slokas/sanskrit/tirupaartthanpallipaasurangal.pdf": pdf_0c14cec62fbba559427257a1f90ba372,
  "https://www.prapatti.com/slokas/english/tiruppavalavannampaasurangal.pdf": pdf_da976f5b4ff7da23e78f079af1ddc85b,
  "https://www.prapatti.com/slokas/sanskrit/tiruppavalavannampaasurangal.pdf": pdf_53cc8d90c0c2a98c11550c567ff43b01,
  "https://www.prapatti.com/slokas/tamil/tiruppavalavannampaasurangal.pdf": pdf_2a8cef0bb0454d301112d16d9efa92e5,
  "https://www.prapatti.com/slokas/kannada/tiruppavalavannampaasurangal.pdf": pdf_8613457a948e834ebff3739ea5a1e113,
  "https://www.prapatti.com/slokas/sanskrit/tirupperaipaasurangal.pdf": pdf_de6bb208d838f5dfd5a86e0c056f4dd6,
  "https://www.prapatti.com/slokas/kannada/tirupperaipaasurangal.pdf": pdf_0518ec4a2bde5988bc0ac91095416223,
  "https://www.prapatti.com/slokas/english/tirupperaipaasurangal.pdf": pdf_fe42f7ebd4f56af5f506f3d77be3233f,
  "https://www.prapatti.com/slokas/tamil/tirupperaipaasurangal.pdf": pdf_1d4c49d8d9c0681c060660406acd5979,
  "https://www.prapatti.com/slokas/tamil/tiruppirudipaasurangal.pdf": pdf_f64cb7edf42094ebb4ca60da940bf0a9,
  "https://www.prapatti.com/slokas/english/tiruppirudipaasurangal.pdf": pdf_e925fe71bcc2648c5cfa82d17fd16959,
  "https://www.prapatti.com/slokas/sanskrit/tiruppirudipaasurangal.pdf": pdf_515dbb073a2ef7addd267357bde5b0de,
  "https://www.prapatti.com/slokas/kannada/tiruppirudipaasurangal.pdf": pdf_d415b79673b64a9700e75a92315bed3b,
  "https://www.prapatti.com/slokas/english/tiruppulingudipaasurangal.pdf": pdf_d91883239caf106bd38b029b56d37b25,
  "https://www.prapatti.com/slokas/sanskrit/tiruppulingudipaasurangal.pdf": pdf_9ac625846802113082b73d5d6b7122e4,
  "https://www.prapatti.com/slokas/kannada/tiruppulingudipaasurangal.pdf": pdf_0e4b2addb7266ebb729060d820b7ac0e,
  "https://www.prapatti.com/slokas/tamil/tiruppulingudipaasurangal.pdf": pdf_8f7adfe35af3e2ae271addc7d60a6263,
  "https://www.prapatti.com/slokas/tamil/tiruppullambhuutangudipaasurangal.pdf": pdf_193bca96df35d7c6966fc26e46226ee2,
  "https://www.prapatti.com/slokas/sanskrit/tiruppullambhuutangudipaasurangal.pdf": pdf_10b9839c72dec2b6257c3d83b0b54e5e,
  "https://www.prapatti.com/slokas/english/tiruppullambhuutangudipaasurangal.pdf": pdf_e5f384c1f617f9e06e11e886acfdfb92,
  "https://www.prapatti.com/slokas/kannada/tiruppullambhuutangudipaasurangal.pdf": pdf_7dbb4d842436bd664895ad69a5140c9b,
  "https://www.prapatti.com/slokas/kannada/tiruppuliyuurpaasurangal.pdf": pdf_b1448c6194802eea6c4608bdb6ca4d59,
  "https://www.prapatti.com/slokas/tamil/tiruppuliyuurpaasurangal.pdf": pdf_442c0198d51141a68137614ccd5951ba,
  "https://www.prapatti.com/slokas/english/tiruppuliyuurpaasurangal.pdf": pdf_70003b24276b7236ba1eeb501755b774,
  "https://www.prapatti.com/slokas/sanskrit/tiruppuliyuurpaasurangal.pdf": pdf_6dfdf2b33193820cb2e679cb196c8808,
  "https://www.prapatti.com/slokas/tamil/tiruppullaanipaasurangal.pdf": pdf_216a925d4828aba34c29c9b3311f438d,
  "https://www.prapatti.com/slokas/english/tiruppullaanipaasurangal.pdf": pdf_806f334afd9247a7f6dcbb050caddbc2,
  "https://www.prapatti.com/slokas/kannada/tiruppullaanipaasurangal.pdf": pdf_dfb9ff72c974cd705c7c95a75ccdff8f,
  "https://www.prapatti.com/slokas/sanskrit/tiruppullaanipaasurangal.pdf": pdf_cbcd6e82328dd8123047c76f0ea18f97,
  "https://www.prapatti.com/slokas/tamil/tirupputkuzipaasurangal.pdf": pdf_1895f6554a0c5b93bdf4423b69d09b9a,
  "https://www.prapatti.com/slokas/kannada/tirupputkuzipaasurangal.pdf": pdf_c8b6e95f750c0b0a090f9a33c029a8eb,
  "https://www.prapatti.com/slokas/sanskrit/tirupputkuzipaasurangal.pdf": pdf_253078ca26a2226235b4cee81da4a4b4,
  "https://www.prapatti.com/slokas/english/tirupputkuzipaasurangal.pdf": pdf_3c2410a55122b91cee3fc3fa874e15fe,
  "https://www.prapatti.com/slokas/sanskrit/tirucemponceykoyilpaasurangal.pdf": pdf_a8ce2970b68bd8ff5127236fcd82f9fb,
  "https://www.prapatti.com/slokas/tamil/tirucemponceykoyilpaasurangal.pdf": pdf_44317740b2a4f78fb29b18836b4b1e32,
  "https://www.prapatti.com/slokas/english/tirucemponceykoyilpaasurangal.pdf": pdf_0eacfd9e656b2d3a7851467032315f03,
  "https://www.prapatti.com/slokas/kannada/tirucemponceykoyilpaasurangal.pdf": pdf_df8dd9f8510ae6d74e327ebc6c789378,
  "https://www.prapatti.com/slokas/kannada/tiruttolaivillimangalampaasurangal.pdf": pdf_98da025671f595afe9dbcc3ffff3f3e9,
  "https://www.prapatti.com/slokas/tamil/tiruttolaivillimangalampaasurangal.pdf": pdf_34e6a75d39d9b414062d7e3f7aefbe9b,
  "https://www.prapatti.com/slokas/sanskrit/tiruttolaivillimangalampaasurangal.pdf": pdf_cf42d45b14848d59aea477b27e29276a,
  "https://www.prapatti.com/slokas/english/tiruttolaivillimangalampaasurangal.pdf": pdf_42dbd71c29790101561beb9092fd3fe1,
  "https://www.prapatti.com/slokas/sanskrit/tiruttankaapaasurangal.pdf": pdf_a09fb087b98e330bf86358927f3b1c41,
  "https://www.prapatti.com/slokas/english/tiruttankaapaasurangal.pdf": pdf_9bd3d433a82e79004e395409fe21de5c,
  "https://www.prapatti.com/slokas/kannada/tiruttankaapaasurangal.pdf": pdf_e229a3bd8ab6a2414caae7855a26d5c9,
  "https://www.prapatti.com/slokas/tamil/tiruttankaapaasurangal.pdf": pdf_5049973c54b103f0969dc9a8934b1d29,
  "https://www.prapatti.com/slokas/sanskrit/tirumanikkuudampaasurangal.pdf": pdf_6b8fa3c60a0fc1c8b0cfa2f9de2f18a0,
  "https://www.prapatti.com/slokas/english/tiruttetriyambalampaasurangal.pdf": pdf_a65df048140e685a937d2e1644ebf9db,
  "https://www.prapatti.com/slokas/tamil/tirumanikkuudampaasurangal.pdf": pdf_14a641ffd27b02d79ae329c5ac5e82eb,
  "https://www.prapatti.com/slokas/kannada/tirumanikkuudampaasurangal.pdf": pdf_ff3811ee99dfe6e076eeffee81cd85db,
  "https://www.prapatti.com/slokas/tamil/tiruttetriyambalampaasurangal.pdf": pdf_a71825ffe35310bcefd6c3edad884e21,
  "https://www.prapatti.com/slokas/sanskrit/tiruttetriyambalampaasurangal.pdf": pdf_07e2de65c1cf1e3def591f6184e5bdbf,
  "https://www.prapatti.com/slokas/english/tirumanikkuudampaasurangal.pdf": pdf_594440a2f1d55d2b47ccfcfe3808e781,
  "https://www.prapatti.com/slokas/kannada/tiruttetriyambalampaasurangal.pdf": pdf_6c1b76c32b2f75a9a572e1678860b6f2,
  "https://www.prapatti.com/slokas/sanskrit/tiruttankaalpaasurangal.pdf": pdf_973c9239f43d2ca5d105542b86a3e7c3,
  "https://www.prapatti.com/slokas/english/tiruttankaalpaasurangal.pdf": pdf_0d1c8c67946f32def406c096f0db1493,
  "https://www.prapatti.com/slokas/kannada/tiruttankaalpaasurangal.pdf": pdf_c2da880957dab0f800bfb3ace5e2a673,
  "https://www.prapatti.com/slokas/tamil/tiruttankaalpaasurangal.pdf": pdf_51dc9208b5b46f837599c0384ab29e0a,
  "https://www.prapatti.com/slokas/tamil/tiruvaalitirunagaripaasurangal.pdf": pdf_a34cc35c3cd289a937b00f319079eae1,
  "https://www.prapatti.com/slokas/sanskrit/tiruvaalitirunagaripaasurangal.pdf": pdf_a6ce697ab758562181cd6256fb3f8abf,
  "https://www.prapatti.com/slokas/english/tiruvaalitirunagaripaasurangal.pdf": pdf_559e4652faba9025b14825682281aca8,
  "https://www.prapatti.com/slokas/kannada/tiruvaalitirunagaripaasurangal.pdf": pdf_b6388d68fa99c96eb84610c6974436dc,
  "https://www.prapatti.com/slokas/kannada/tiruvaaranvilaipaasurangal.pdf": pdf_1c0d4b032ff1bd6a9c2aa7e71e95088e,
  "https://www.prapatti.com/slokas/english/tiruvaaranvilaipaasurangal.pdf": pdf_511c56741841944c240656364a3e5755,
  "https://www.prapatti.com/slokas/tamil/tiruvaaranvilaipaasurangal.pdf": pdf_9c4888a40e6d7f82d642b04ffb6bb6a3,
  "https://www.prapatti.com/slokas/sanskrit/tiruvaaranvilaipaasurangal.pdf": pdf_674b69642085592b18d65d67d65155fc,
  "https://www.prapatti.com/slokas/tamil/tiruvadamaduraipaasurangal.pdf": pdf_bea57131380e0127f53d58c93ba4a362,
  "https://www.prapatti.com/slokas/kannada/tiruvadamaduraipaasurangal.pdf": pdf_3475e2c8876e9f81ad48975160c5c4e4,
  "https://www.prapatti.com/slokas/sanskrit/tiruvadamaduraipaasurangal.pdf": pdf_937e7fa2e9487e02fa69f216fa5d17c2,
  "https://www.prapatti.com/slokas/english/tiruvadamaduraipaasurangal.pdf": pdf_e7e8a2bb9c7a317fa0be8d74d3f44684,
  "https://www.prapatti.com/slokas/english/tiruvadariyaashramampaasurangal.pdf": pdf_570aa3e81d8d02c5a3dc883e4c5e6739,
  "https://www.prapatti.com/slokas/sanskrit/tiruvadariyaashramampaasurangal.pdf": pdf_e22ab3a960795caa8f472c95f1d7e5d3,
  "https://www.prapatti.com/slokas/kannada/tiruvadariyaashramampaasurangal.pdf": pdf_1fc15dc30e1eb2b90fa760bc3646d1f0,
  "https://www.prapatti.com/slokas/tamil/tiruvadariyaashramampaasurangal.pdf": pdf_a573e27e70898aaafeba4b2bfb4336a9,
  "https://www.prapatti.com/slokas/kannada/tiruvahiindirapurampaasurangal.pdf": pdf_d4962e9b5f024e588cb28f97530429e6,
  "https://www.prapatti.com/slokas/english/tiruvahiindirapurampaasurangal.pdf": pdf_ddc2599bd44ec20c7eb9de076e65abaa,
  "https://www.prapatti.com/slokas/tamil/tiruvahiindirapurampaasurangal.pdf": pdf_afca1ac5fed63986ee0def218dba7154,
  "https://www.prapatti.com/slokas/sanskrit/tiruvahiindirapurampaasurangal.pdf": pdf_13ffa4a4a8dd28c11b994caf3154d5a5,
  "https://www.prapatti.com/slokas/english/tiruvaikundampaasurangal.pdf": pdf_e33210d1603eb6931c1d357abb01a23f,
  "https://www.prapatti.com/slokas/kannada/tiruvaikundampaasurangal.pdf": pdf_a7206c105aa23d94404aeaafe59720b6,
  "https://www.prapatti.com/slokas/tamil/tiruvaikundampaasurangal.pdf": pdf_2184f393e8888df83309ab52eec797d6,
  "https://www.prapatti.com/slokas/sanskrit/tiruvaikundampaasurangal.pdf": pdf_96a3749346b339333a353b8743044492,
  "https://www.prapatti.com/slokas/english/tiruvaikundavinnagarampaasurangal.pdf": pdf_2ee544cf0fd79487eb548cc4cbd6dc3f,
  "https://www.prapatti.com/slokas/sanskrit/tiruvaikundavinnagarampaasurangal.pdf": pdf_147d5ec7c2884d418b082dffd2a33500,
  "https://www.prapatti.com/slokas/tamil/tiruvaikundavinnagarampaasurangal.pdf": pdf_8c84b55c994bae6e3059cb8048df33f1,
  "https://www.prapatti.com/slokas/kannada/tiruvaikundavinnagarampaasurangal.pdf": pdf_5b4135b44fe275b7f845319f25e74999,
  "https://www.prapatti.com/slokas/sanskrit/tiruvaayppaadipaasurangal.pdf": pdf_74437a9ab81898010c3ccb1e782d3142,
  "https://www.prapatti.com/slokas/english/tiruvaayppaadipaasurangal.pdf": pdf_a0144544249c4f64dbf649d8e9974e28,
  "https://www.prapatti.com/slokas/tamil/tiruvaayppaadipaasurangal.pdf": pdf_56968eb76429aa57006bc2090972650e,
  "https://www.prapatti.com/slokas/kannada/tiruvaayppaadipaasurangal.pdf": pdf_66d33cfe529ce0921efb82d8187d1bfb,
  "https://www.prapatti.com/slokas/sanskrit/tiruvallavaazpaasurangal.pdf": pdf_5de99fc3921db60d153e493f01a1c78c,
  "https://www.prapatti.com/slokas/tamil/tiruvallavaazpaasurangal.pdf": pdf_ea6ae09b6db0f952fda275c78e4a2a0b,
  "https://www.prapatti.com/slokas/kannada/tiruvallavaazpaasurangal.pdf": pdf_c117f24a02c439107d959df8b8063e2a,
  "https://www.prapatti.com/slokas/english/tiruvallavaazpaasurangal.pdf": pdf_acfa9ff7abacc8e610d8ec8b958596f5,
  "https://www.prapatti.com/slokas/tamil/tiruvallikkenipaasurangal.pdf": pdf_4c92bb0ac189f607e00dd53f65e0b84d,
  "https://www.prapatti.com/slokas/english/tiruvallikkenipaasurangal.pdf": pdf_af6ce22ac982da5701725249ab3ee5c8,
  "https://www.prapatti.com/slokas/sanskrit/tiruvallikkenipaasurangal.pdf": pdf_9de09b30131765866e6dab287ff57160,
  "https://www.prapatti.com/slokas/kannada/tiruvallikkenipaasurangal.pdf": pdf_f4de409bfdf951fdc6dafe50dc60e9aa,
  "https://www.prapatti.com/slokas/english/tiruvanantapurampaasurangal.pdf": pdf_6937dcf9bddd0f4fe51961374c331015,
  "https://www.prapatti.com/slokas/tamil/tiruvanantapurampaasurangal.pdf": pdf_3c10c2111264057a1f6fe66af586f66b,
  "https://www.prapatti.com/slokas/sanskrit/tiruvanantapurampaasurangal.pdf": pdf_105fd65678c57ed5ac0648756096f357,
  "https://www.prapatti.com/slokas/kannada/tiruvanantapurampaasurangal.pdf": pdf_9173f42e47e403739c064e4692a8abe3,
  "https://www.prapatti.com/slokas/sanskrit/tiruvanbilpaasurangal.pdf": pdf_a997e3565417baeb54536d4c10ef24f3,
  "https://www.prapatti.com/slokas/kannada/tiruvanbilpaasurangal.pdf": pdf_0bc523451cbe5267fa5386780151e3f5,
  "https://www.prapatti.com/slokas/tamil/tiruvanbilpaasurangal.pdf": pdf_29e0acd157a05077c598e4a810886dd3,
  "https://www.prapatti.com/slokas/english/tiruvanbilpaasurangal.pdf": pdf_6a34cfdfbe7f208065a07dd30a7310f8,
  "https://www.prapatti.com/slokas/tamil/tiruvanparisaarampaasurangal.pdf": pdf_da7c451f44ed35a973df3423a3436231,
  "https://www.prapatti.com/slokas/kannada/tiruvanparisaarampaasurangal.pdf": pdf_89eb494aa52a58fe5d9ade25b2ba775f,
  "https://www.prapatti.com/slokas/sanskrit/tiruvanparisaarampaasurangal.pdf": pdf_ed755ea84744585276610b4c8e648280,
  "https://www.prapatti.com/slokas/english/tiruvanparisaarampaasurangal.pdf": pdf_2b70618b1dacad5d02c88fc1a3343a07,
  "https://www.prapatti.com/slokas/sanskrit/tiruvanpurudottamampaasurangal.pdf": pdf_29b8d5169261a83a8976f015d5aa837c,
  "https://www.prapatti.com/slokas/english/tiruvanpurudottamampaasurangal.pdf": pdf_7dae5e8abed1f28831fa0e0cf2cfcd05,
  "https://www.prapatti.com/slokas/tamil/tiruvanpurudottamampaasurangal.pdf": pdf_badf2b022fb7abe16dbdae024c13306b,
  "https://www.prapatti.com/slokas/kannada/tiruvanpurudottamampaasurangal.pdf": pdf_22fc863d0ec8a29b7f98c34fc2fad98c,
  "https://www.prapatti.com/slokas/sanskrit/tiruvanvanduurpaasurangal.pdf": pdf_db57121a22dbc69abf310b056a27fa32,
  "https://www.prapatti.com/slokas/kannada/tiruvanvanduurpaasurangal.pdf": pdf_404c659ca334b6512e7098b7d313e496,
  "https://www.prapatti.com/slokas/english/tiruvanvanduurpaasurangal.pdf": pdf_c887c84c1a7bd098265d0da72d1c7d67,
  "https://www.prapatti.com/slokas/tamil/tiruvanvanduurpaasurangal.pdf": pdf_aae92bfcb68b757c2210658e5db3e415,
  "https://www.prapatti.com/slokas/tamil/tiruvaragunamangaipaasurangal.pdf": pdf_7a96d73dec9090888c8dfa00aedfe609,
  "https://www.prapatti.com/slokas/kannada/tiruvaragunamangaipaasurangal.pdf": pdf_7ee1af8a2242a4dc10473d9859012d12,
  "https://www.prapatti.com/slokas/english/tiruvaragunamangaipaasurangal.pdf": pdf_588858966b0ed6d3e417d19b720c07a3,
  "https://www.prapatti.com/slokas/sanskrit/tiruvaragunamangaipaasurangal.pdf": pdf_a68a7087f910c8f92c511fd46b4ded65,
  "https://www.prapatti.com/slokas/kannada/tiruvaattaarupaasurangal.pdf": pdf_622a656f915f5c271d9b9219016d2db8,
  "https://www.prapatti.com/slokas/english/tiruvaattaarupaasurangal.pdf": pdf_15ff22556ddd3a59ab0f92a2a57a34c0,
  "https://www.prapatti.com/slokas/sanskrit/tiruvaattaarupaasurangal.pdf": pdf_59418b7e2ec390d5760c381e0259a3a2,
  "https://www.prapatti.com/slokas/tamil/tiruvaattaarupaasurangal.pdf": pdf_bc16c690f1f36dbe5142df5c0f0c6955,
  "https://www.prapatti.com/slokas/kannada/tiruvazunduurpaasurangal.pdf": pdf_5a908a37ceb664ca260b277a9d7bf786,
  "https://www.prapatti.com/slokas/tamil/tiruvazunduurpaasurangal.pdf": pdf_8c2e4bcd6670b5696c256ddb5194950a,
  "https://www.prapatti.com/slokas/english/tiruvazunduurpaasurangal.pdf": pdf_73ea64db0d22141eca5c85fe26d78a2b,
  "https://www.prapatti.com/slokas/sanskrit/tiruvazunduurpaasurangal.pdf": pdf_2769c6f5942d2610757dc8db3b076c08,
  "https://www.prapatti.com/slokas/kannada/tiruvekkaapaasurangal.pdf": pdf_2143b9e6e4e17817dbb422abade4af10,
  "https://www.prapatti.com/slokas/sanskrit/tiruvekkaapaasurangal.pdf": pdf_63cd4d3bd80880910d85118f3386e881,
  "https://www.prapatti.com/slokas/english/tiruvekkaapaasurangal.pdf": pdf_39d83999dd93ad120339ba34db20e016,
  "https://www.prapatti.com/slokas/tamil/tiruvekkaapaasurangal.pdf": pdf_9ce69f1b146efcf88ba9a7afbaf068f8,
  "https://www.prapatti.com/slokas/tamil/tiruvellakkulampaasurangal.pdf": pdf_f3ec7d5b53d5a918ceb30c7edb3eb6df,
  "https://www.prapatti.com/slokas/kannada/tiruvellakkulampaasurangal.pdf": pdf_53ff0360737ae049bee0eb1edcd4a2bb,
  "https://www.prapatti.com/slokas/sanskrit/tiruvellakkulampaasurangal.pdf": pdf_e9917d71252b9895517ea1db983cdb54,
  "https://www.prapatti.com/slokas/english/tiruvellakkulampaasurangal.pdf": pdf_50aa504d7947274dec53251f10162e7c,
  "https://www.prapatti.com/slokas/sanskrit/tiruvellaraipaasurangal.pdf": pdf_e142ca0049cb6c27fe4a436f1410edf3,
  "https://www.prapatti.com/slokas/kannada/tiruvellaraipaasurangal.pdf": pdf_68a9d62e4fed82f5c0d86d3e1c6d979c,
  "https://www.prapatti.com/slokas/tamil/tiruvellaraipaasurangal.pdf": pdf_5ebc0cfecc15b133a17610674c1218ae,
  "https://www.prapatti.com/slokas/english/tiruvellaraipaasurangal.pdf": pdf_ad19400366e02050d489e5f1b76a5ce0,
  "https://www.prapatti.com/slokas/tamil/tiruvelliyangudipaasurangal.pdf": pdf_d9b8ffc9ca025fd4553ea238f9e0fc7c,
  "https://www.prapatti.com/slokas/english/tiruvelliyangudipaasurangal.pdf": pdf_fe6457f4e706f42edad3e044f4085d0d,
  "https://www.prapatti.com/slokas/kannada/tiruvelliyangudipaasurangal.pdf": pdf_0cd71410eae980af79d5fd07a2f6483b,
  "https://www.prapatti.com/slokas/sanskrit/tiruvelliyangudipaasurangal.pdf": pdf_17b974f76009c6786e5120fe9ebef8cd,
  "https://www.prapatti.com/slokas/sanskrit/tiruvelukkaipaasurangal.pdf": pdf_a82e137acedde9e26f4ae1d603e2c360,
  "https://www.prapatti.com/slokas/kannada/tiruvelukkaipaasurangal.pdf": pdf_2d4acafce0490672a5426d35533d36b4,
  "https://www.prapatti.com/slokas/tamil/tiruvelukkaipaasurangal.pdf": pdf_c0463749eb870b7aaa019bb24661865f,
  "https://www.prapatti.com/slokas/english/tiruvelukkaipaasurangal.pdf": pdf_c93ed8cdbdcc8fd7e8baec48a9a3f861,
  "https://www.prapatti.com/slokas/sanskrit/tiruvengadampaasurangal.pdf": pdf_dac7b466cebe4c6db8bcfda3d558a060,
  "https://www.prapatti.com/slokas/tamil/tiruvengadampaasurangal.pdf": pdf_c6e4b3479871e4028c9b6737bc4738c0,
  "https://www.prapatti.com/slokas/english/tiruvengadampaasurangal.pdf": pdf_7ebb9f2adbd1ee821a72adb22b205377,
  "https://www.prapatti.com/slokas/kannada/tiruvengadampaasurangal.pdf": pdf_19ceadc8c72c1eba78bf538994aafb73,
  "https://www.prapatti.com/slokas/kannada/tiruvidavendaipaasurangal.pdf": pdf_01bb416cc19b10ec62cd114b623f9440,
  "https://www.prapatti.com/slokas/english/tiruvidavendaipaasurangal.pdf": pdf_48b4a50cec70c230c2aa662c016ba14f,
  "https://www.prapatti.com/slokas/tamil/tiruvidavendaipaasurangal.pdf": pdf_71b6bef84f854b695150983f037e329f,
  "https://www.prapatti.com/slokas/sanskrit/tiruvidavendaipaasurangal.pdf": pdf_ffa4ca4febcfcfa86cb17fa6ee5c6143,
  "https://www.prapatti.com/slokas/sanskrit/tiruvinnagarampaasurangal.pdf": pdf_556036ba904756bbc3685ffbc21bf495,
  "https://www.prapatti.com/slokas/tamil/tiruvinnagarampaasurangal.pdf": pdf_010398f3f1d51b95dc12cb06bc17a417,
  "https://www.prapatti.com/slokas/english/tiruvinnagarampaasurangal.pdf": pdf_0bfa3fcb9bcd3e1af235604de08ab75a,
  "https://www.prapatti.com/slokas/kannada/tiruvinnagarampaasurangal.pdf": pdf_9f9ce71426811aca26bd023d2ad0a600,
  "https://www.prapatti.com/slokas/kannada/tiruvittuvakkodupaasurangal.pdf": pdf_a8af8bb3e166ba4d93884bc9df6ab63b,
  "https://www.prapatti.com/slokas/tamil/tiruvittuvakkodupaasurangal.pdf": pdf_aedd6f489aee7ccd50cc4fd74eba34fc,
  "https://www.prapatti.com/slokas/english/tiruvittuvakkodupaasurangal.pdf": pdf_f616b3ff094894e5af1028bfb41b8bb9,
  "https://www.prapatti.com/slokas/sanskrit/tiruvittuvakkodupaasurangal.pdf": pdf_c0339bcd26ce2e3b12ab5a6967959e5a,
};
