import { z } from "zod";
import { BOOK_PAYLOAD_SCHEMA_VERSION, MobileBookSchema, MobileChapterSummarySchema } from "./mobile-content.ts";

/**
 * The public catalog manifest that lets an ALREADY-INSTALLED mobile app
 * discover new or changed Library content without a new APK -- the
 * "expandable content" half of the two delivery models this repo uses
 * (see mobile/services/pasuramArchive.ts's own doc comment for the
 * other: Pasurams are core, bundled, and never described by this file
 * as a way to obtain them).
 *
 * Generated by scripts/build-content-manifest.ts (web repo root, run in
 * `prebuild` after scripts/build-book-payloads.ts, whose output --
 * public/books/<slug>.json -- this script hashes and sizes), published
 * as public/content-manifest.json on the same GitHub Pages deploy that
 * already serves app-version.json and every book payload. Fetched by
 * mobile/services/libraryCatalogService.ts.
 *
 * Deliberately a SEPARATE concept from public/app-version.json (see
 * mobile/services/updateCheckService.ts): that file answers "is a newer
 * APK/AAB available", checked against this build's own native
 * versionCode, with no silent-install path -- a person has to tap
 * through an install themselves. This file answers "is newer CONTENT
 * available for a book the app already knows how to render", checked
 * against each book's own contentHash, and CAN be silently obtained and
 * applied because it is data a already-installed, schema-compatible app
 * fully understands, not code.
 *
 * `contentManifestVersion` is this file's OWN format version (the shape
 * of the manifest itself: which fields exist, what `books[]` contains) --
 * NOT `contentSchemaVersion` (BOOK_PAYLOAD_SCHEMA_VERSION), which is the
 * format version of each book's own downloadable payload
 * (public/books/<slug>.json) and is already enforced independently by
 * BookPayloadSchema's `z.literal(...)` wherever that payload is parsed
 * (mobile/services/bookOfflineCore.ts's readValidBookPayload). Keeping
 * them distinct means a future manifest-shape change and a future
 * book-payload-shape change can each roll out on their own schedule.
 * Both are still `z.literal(...)`, not a range check: an older,
 * still-installed app whose bundled Zod schema expects literal 1 will
 * simply fail to parse a manifest or payload published with version 2,
 * which mobile/services/libraryCatalogService.ts treats exactly like
 * "unreachable" -- keep whatever was already working, never crash, never
 * silently accept a shape it doesn't understand (Part 13 of the
 * architecture spec this file implements).
 */
export const CONTENT_MANIFEST_VERSION = 1;

export const ContentManifestBookEntrySchema = z.object({
  book: MobileBookSchema,
  /** Lightweight per-chapter catalog data (title/slug/order/status) -- searchable and displayable before this book has ever been downloaded. Never a chapter body; see MobileChapterSummarySchema's own doc comment. */
  chapters: z.array(MobileChapterSummarySchema),
  /** The `contentSchemaVersion` literal this book's own public/books/<slug>.json payload was published with -- always BOOK_PAYLOAD_SCHEMA_VERSION today, carried explicitly so a future incompatible payload version is visible in the manifest itself, before a download is even attempted. */
  payloadSchemaVersion: z.literal(BOOK_PAYLOAD_SCHEMA_VERSION),
  /** SHA-256 (mobile/services/sha256.ts) of the exact bytes at `url` -- the one field mobile/services/libraryCatalogCore.ts compares against a downloaded book's own locally-recorded hash to decide whether a re-sync is needed. Changes whenever the book's content changes in any way; unrelated to `payloadSchemaVersion`, which only changes on an intentional payload-shape migration. */
  contentHash: z.string().regex(/^[0-9a-f]{64}$/),
  byteSize: z.number().int().nonnegative(),
  url: z.string().min(1),
  updatedAt: z.string().min(1),
});
export type ContentManifestBookEntry = z.infer<typeof ContentManifestBookEntrySchema>;

export const ContentManifestSchema = z.object({
  contentManifestVersion: z.literal(CONTENT_MANIFEST_VERSION),
  generatedAt: z.string().min(1),
  books: z.array(ContentManifestBookEntrySchema),
});
export type ContentManifest = z.infer<typeof ContentManifestSchema>;
